/* Auto-generated by gen-static-libs.py — DO NOT EDIT.
 *
 * Regenerate with:
 *   python3 gen-static-libs.py /ikvm/bin/libiava.so:out/native/libiava.a /ikvm/bin/libzip.so:out/native/libzip.a /ikvm/bin/libnio.so:out/native/libnio.a /ikvm/vin/libnet.so:out/native/libnet.a
 *
 * Defines jvm_static_libs[], the registry used by jvm_emscripten_dynlib.c to
 * implement JVM_LoadLibrary / JVM_FindLibraryEntry without dlsym() or
 * -sMAIN_MODULE.  Each per-library symbol table was produced by running:
 *   /usr/bin/llvm-nm --defined-only --extern-only <archive>
 *
 * To add a library, re-run gen-static-libs.py with the new FAKE_PATH:ARCHIVE
 * pair.  To add symbols to an existing library, recompile the archive and
 * re-run the script.
 */

#include <stddef.h>  /* NULL */


/*
 * jvm_emscripten_dynlib.h
 *
 * Shared types and declarations for the Emscripten static library registry.
 * Included by both jvm_emscripten_dynlib.c (the logic) and by the .c file
 * produced by gen-static-libs.py (the data).
 */

#ifndef JVM_EMSCRIPTEN_DYNLIB_H
#define JVM_EMSCRIPTEN_DYNLIB_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * One symbol entry in a per-library lookup table.
 * name - the symbol name passed to JVM_FindLibraryEntry (e.g. "Java_Foo_bar")
 * ptr  - address of the symbol as resolved at compile time via a forward
 *        declaration in the generated file; stored as void* so that
 *        JVM_FindLibraryEntry can return it directly to the JNI caller.
 */
typedef struct {
    const char *name;
    void       *ptr;
} jvm_symbol_entry_t;

/*
 * One entry per statically-linked library.
 * path    - the exact string Java passes to JVM_LoadLibrary (e.g. "libjava.so"
 *           or the full path Java's launcher resolves to)
 * symbols - NULL-terminated array of symbol entries for this library,
 *           generated by gen-static-libs.py from llvm-nm output; NULL if the
 *           library was registered without an archive (empty symbol table).
 */
typedef struct {
    const char               *path;
    const jvm_symbol_entry_t *symbols;
} jvm_static_lib_entry_t;

/* Defined in the file generated by gen-static-libs.py */
extern const jvm_static_lib_entry_t jvm_static_libs[];
extern const int jvm_static_libs_count;

#ifdef __cplusplus
}
#endif

#endif /* JVM_EMSCRIPTEN_DYNLIB_H */


/* Forward declarations of every symbol referenced below.
 * Using empty parameter lists (K&R style) so the declarations
 * are compatible with any actual JNI signature without needing
 * prototypes.  The cast to void* is done in the tables below. */
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpedantic"
#pragma clang diagnostic ignored "-Wstrict-prototypes"

extern void JDK_execvpe();
extern void childProcess();
extern void closeDescriptors();
extern void closeSafely();
extern void execve_as_traditional_shell_script();
extern void execve_with_shell_fallback();
extern void initVectorFromBlock();
extern void isAsciiDigit();
extern void magicNumber();
extern void moveDescriptor();
extern void readFully();
extern void restartableDup2();
extern void restartableWrite();
extern void GetJavaProperties();
extern void GetStringPlatform();
extern void Java_java_lang_ProcessEnvironment_environ();
extern void Java_java_lang_UNIXProcess_destroyProcess();
extern void Java_java_lang_UNIXProcess_forkAndExec();
extern void Java_java_lang_UNIXProcess_init();
extern void Java_java_lang_UNIXProcess_waitForProcessExit();
extern void Java_java_lang_Double_doubleToRawLongBits();
extern void Java_java_lang_Double_longBitsToDouble();
extern void Java_java_lang_Float_floatToRawIntBits();
extern void Java_java_lang_Float_intBitsToFloat();
extern void Java_java_lang_StrictMath_IEEEremainder();
extern void Java_java_lang_StrictMath_acos();
extern void Java_java_lang_StrictMath_asin();
extern void Java_java_lang_StrictMath_atan();
extern void Java_java_lang_StrictMath_atan2();
extern void Java_java_lang_StrictMath_cbrt();
extern void Java_java_lang_StrictMath_cos();
extern void Java_java_lang_StrictMath_cosh();
extern void Java_java_lang_StrictMath_exp();
extern void Java_java_lang_StrictMath_expm1();
extern void Java_java_lang_StrictMath_hypot();
extern void Java_java_lang_StrictMath_log();
extern void Java_java_lang_StrictMath_log10();
extern void Java_java_lang_StrictMath_log1p();
extern void Java_java_lang_StrictMath_pow();
extern void Java_java_lang_StrictMath_sin();
extern void Java_java_lang_StrictMath_sinh();
extern void Java_java_lang_StrictMath_sqrt();
extern void Java_java_lang_StrictMath_tan();
extern void Java_java_lang_StrictMath_tanh();
extern void Java_java_lang_System_identityHashCode();
extern void Java_java_lang_System_initProperties();
extern void Java_java_lang_System_mapLibraryName();
extern void Java_java_lang_System_registerNatives();
extern void Java_java_lang_System_setErr0();
extern void Java_java_lang_System_setIn0();
extern void Java_java_lang_System_setOut0();
extern void fillI18nProps();
extern void Java_java_lang_reflect_Proxy_defineClass0();
extern void __j__ieee754_acos();
extern void __j__ieee754_asin();
extern void __j__ieee754_atan2();
extern void __j__ieee754_atanh();
extern void __j__ieee754_cosh();
extern void __j__ieee754_exp();
extern void __j__ieee754_fmod();
extern void __j__ieee754_hypot();
extern void __j__ieee754_log10();
extern void __j__ieee754_log();
extern void __j__ieee754_pow();
extern void __j__ieee754_remainder();
extern void __j__ieee754_rem_pio2();
extern void __j__ieee754_scalb();
extern void __j__ieee754_sinh();
extern void __j__ieee754_sqrt();
extern void __j__kernel_cos();
extern void __j__kernel_rem_pio2();
extern void __j__kernel_sin();
extern void __j__kernel_standard();
extern void __j__kernel_tan();
extern void jatan();
extern void jcbrt();
extern void jceil();
extern void copysign();
extern void jcos();
extern void jexpm1();
extern void jfabs();
extern void finite();
extern void jfloor();
extern void frexp();
extern void ilogb();
extern void isnan();
extern void ldexp();
extern void jlog1p();
extern void logb();
extern void matherr();
extern void modf();
extern void nextafter();
extern void rint();
extern void scalbn();
extern void significand();
extern void jsin();
extern void jtan();
extern void jtanh();
extern void jacos();
extern void jasin();
extern void jatan2();
extern void atanh();
extern void jcosh();
extern void jexp();
extern void jmod();
extern void jhypot();
extern void jlog10();
extern void jlog();
extern void jpow();
extern void jremainder();
extern void scalb();
extern void jsinh();
extern void jsqrt();
extern void Java_java_io_FileInputStream_available0();
extern void Java_java_io_FileInputStream_initIDs();
extern void Java_java_io_FileInputStream_open0();
extern void Java_java_io_FileInputStream_read0();
extern void Java_java_io_FileInputStream_readBytes();
extern void Java_java_io_FileInputStream_skip0();
extern void readBytes();
extern void readSingle();
extern void throwFileNotFoundException();
extern void writeBytes();
extern void writeSingle();
extern void Java_java_io_ObjectInputStream_bytesToDoubles();
extern void Java_java_io_ObjectInputStream_bytesToFloats();
extern void Java_java_io_ObjectOutputStream_doublesToBytes();
extern void Java_java_io_ObjectOutputStream_floatsToBytes();
extern void Java_java_io_ObjectStreamClass_hasStaticInitializer();
extern void Java_java_io_ObjectStreamClass_initNative();
extern void Java_java_io_RandomAccessFile_getFilePointer();
extern void Java_java_io_RandomAccessFile_initIDs();
extern void Java_java_io_RandomAccessFile_length();
extern void Java_java_io_RandomAccessFile_open0();
extern void Java_java_io_RandomAccessFile_read0();
extern void Java_java_io_RandomAccessFile_readBytes();
extern void Java_java_io_RandomAccessFile_seek0();
extern void Java_java_io_RandomAccessFile_setLength();
extern void Java_java_io_RandomAccessFile_write0();
extern void Java_java_io_RandomAccessFile_writeBytes();
extern void canonicalize();
extern void Java_java_io_Console_echo();
extern void Java_java_io_Console_encoding();
extern void Java_java_io_Console_istty();
extern void Java_java_io_FileDescriptor_initIDs();
extern void Java_java_io_FileDescriptor_sync();
extern void Java_java_io_FileInputStream_close0();
extern void Java_java_io_FileOutputStream_close0();
extern void Java_java_io_FileOutputStream_initIDs();
extern void Java_java_io_FileOutputStream_open0();
extern void Java_java_io_FileOutputStream_write();
extern void Java_java_io_FileOutputStream_writeBytes();
extern void fileClose();
extern void fileOpen();
extern void getLastErrorString();
extern void handleAvailable();
extern void handleOpen();
extern void handleRead();
extern void handleSetLength();
extern void handleWrite();
extern void Java_java_io_RandomAccessFile_close0();
extern void Java_java_io_UnixFileSystem_canonicalize0();
extern void Java_java_io_UnixFileSystem_checkAccess();
extern void Java_java_io_UnixFileSystem_createDirectory();
extern void Java_java_io_UnixFileSystem_createFileExclusively();
extern void Java_java_io_UnixFileSystem_delete0();
extern void Java_java_io_UnixFileSystem_getBooleanAttributes0();
extern void Java_java_io_UnixFileSystem_getLastModifiedTime();
extern void Java_java_io_UnixFileSystem_getLength();
extern void Java_java_io_UnixFileSystem_getSpace();
extern void Java_java_io_UnixFileSystem_initIDs();
extern void Java_java_io_UnixFileSystem_list();
extern void Java_java_io_UnixFileSystem_rename0();
extern void Java_java_io_UnixFileSystem_setLastModifiedTime();
extern void Java_java_io_UnixFileSystem_setPermission();
extern void Java_java_io_UnixFileSystem_setReadOnly();
extern void Java_java_nio_Bits_copySwapMemory0();
extern void VerifyClassname();
extern void VerifyFixClassname();
extern void JNI_OnLoad();
extern void JDK_GetVersionInfo0();
extern void jio_fprintf();
extern void jio_snprintf();
extern void Canonicalize();
extern void GetStringPlatformChars();
extern void JNU_CallMethodByName();
extern void JNU_CallMethodByNameV();
extern void JNU_CallStaticMethodByName();
extern void JNU_ClassClass();
extern void JNU_ClassObject();
extern void JNU_ClassString();
extern void JNU_ClassThrowable();
extern void JNU_CopyObjectArray();
extern void JNU_Equals();
extern void JNU_GetEnv();
extern void JNU_GetFieldByName();
extern void JNU_GetStaticFieldByName();
extern void JNU_GetStringPlatformChars();
extern void JNU_IsInstanceOfByName();
extern void JNU_MonitorWait();
extern void JNU_NewObjectByName();
extern void JNU_NewStringPlatform();
extern void JNU_Notify();
extern void JNU_NotifyAll();
extern void JNU_PrintClass();
extern void JNU_PrintString();
extern void JNU_ReleaseStringPlatformChars();
extern void JNU_SetFieldByName();
extern void JNU_SetStaticFieldByName();
extern void JNU_ThrowArrayIndexOutOfBoundsException();
extern void JNU_ThrowByName();
extern void JNU_ThrowByNameWithLastError();
extern void JNU_ThrowByNameWithMessageAndLastError();
extern void JNU_ThrowClassNotFoundException();
extern void JNU_ThrowIOException();
extern void JNU_ThrowIOExceptionWithLastError();
extern void JNU_ThrowIllegalAccessError();
extern void JNU_ThrowIllegalAccessException();
extern void JNU_ThrowIllegalArgumentException();
extern void JNU_ThrowInstantiationException();
extern void JNU_ThrowInternalError();
extern void JNU_ThrowNoSuchFieldError();
extern void JNU_ThrowNoSuchFieldException();
extern void JNU_ThrowNoSuchMethodError();
extern void JNU_ThrowNoSuchMethodException();
extern void JNU_ThrowNullPointerException();
extern void JNU_ThrowNumberFormatException();
extern void JNU_ThrowOutOfMemoryError();
extern void JNU_ThrowStringIndexOutOfBoundsException();
extern void JNU_ToString();
extern void NewStringPlatform();
extern void getFastEncoding();
extern void initializeEncoding();
extern void Java_sun_misc_MessageUtils_toStderr();
extern void Java_sun_misc_MessageUtils_toStdout();
extern void Java_sun_misc_NativeSignalHandler_handle0();
extern void Java_sun_misc_Version_getJdkSpecialVersion();
extern void Java_sun_misc_Version_getJdkVersionInfo();
extern void Java_sun_misc_Version_getJvmSpecialVersion();
extern void Java_sun_misc_Version_getJvmVersionInfo();
extern void Java_sun_misc_VMSupport_getVMTemporaryDirectory();
extern void Java_sun_misc_VMSupport_initAgentProperties();
extern void Java_java_util_TimeZone_getSystemGMTOffsetID();
extern void Java_java_util_TimeZone_getSystemTimeZoneID();
extern void JDK_FindJvmEntry();
extern void JDK_InitJvmHandle();
extern void buildJniFunctionName();
extern void getErrorString();
extern void getProcessHandle();
extern void nativeGetStringPlatformChars();
extern void nativeNewStringPlatform();
extern void Java_java_util_prefs_FileSystemPreferences_chmod();
extern void Java_java_util_prefs_FileSystemPreferences_lockFile0();
extern void Java_java_util_prefs_FileSystemPreferences_unlockFile0();
extern void Java_java_util_logging_FileHandler_isSetUID();
extern void findJavaTZ_md();
extern void getGMTOffsetID();
extern void Java_jdk_internal_platform_CgroupMetrics_getTotalMemorySize0();
extern void Java_jdk_internal_platform_CgroupMetrics_isUseContainerSupport();
extern void Java_java_util_zip_Adler32_update();
extern void Java_java_util_zip_Adler32_updateByteBuffer();
extern void Java_java_util_zip_Adler32_updateBytes();
extern void Java_java_util_zip_CRC32_update();
extern void Java_java_util_zip_CRC32_updateByteBuffer();
extern void Java_java_util_zip_CRC32_updateBytes();
extern void ZIP_CRC32();
extern void Java_java_util_zip_Deflater_deflateBytes();
extern void Java_java_util_zip_Deflater_end();
extern void Java_java_util_zip_Deflater_getAdler();
extern void Java_java_util_zip_Deflater_init();
extern void Java_java_util_zip_Deflater_initIDs();
extern void Java_java_util_zip_Deflater_reset();
extern void Java_java_util_zip_Deflater_setDictionary();
extern void Java_java_util_zip_Inflater_end();
extern void Java_java_util_zip_Inflater_getAdler();
extern void Java_java_util_zip_Inflater_inflateBytes();
extern void Java_java_util_zip_Inflater_init();
extern void Java_java_util_zip_Inflater_initIDs();
extern void Java_java_util_zip_Inflater_reset();
extern void Java_java_util_zip_Inflater_setDictionary();
extern void InflateFully();
extern void ZIP_Close();
extern void ZIP_FindEntry();
extern void ZIP_FreeEntry();
extern void ZIP_GetEntry();
extern void ZIP_GetEntry2();
extern void ZIP_GetEntryDataOffset();
extern void ZIP_GetNextEntry();
extern void ZIP_Get_From_Cache();
extern void ZIP_Lock();
extern void ZIP_Open();
extern void ZIP_Open_Generic();
extern void ZIP_Put_In_Cache();
extern void ZIP_Put_In_Cache0();
extern void ZIP_Read();
extern void ZIP_ReadEntry();
extern void ZIP_Unlock();
extern void equals();
extern void compress();
extern void compress2();
extern void compressBound();
extern void deflate();
extern void deflateBound();
extern void deflateCopy();
extern void deflateEnd();
extern void deflateGetDictionary();
extern void deflateInit2_();
extern void deflateInit_();
extern void deflateParams();
extern void deflatePending();
extern void deflatePrime();
extern void deflateReset();
extern void deflateResetKeep();
extern void deflateSetDictionary();
extern void deflateSetHeader();
extern void deflateTune();
extern void gzclose();
extern void gz_error();
extern void gz_intmax();
extern void gzbuffer();
extern void gzclearerr();
extern void gzdopen();
extern void gzeof();
extern void gzerror();
extern void gzoffset();
extern void gzoffset64();
extern void gzopen();
extern void gzopen64();
extern void gzrewind();
extern void gzseek();
extern void gzseek64();
extern void gztell();
extern void gztell64();
extern void gzclose_r();
extern void gzdirect();
extern void gzfread();
extern void gzgetc();
extern void gzgetc_();
extern void gzgets();
extern void gzread();
extern void gzungetc();
extern void gzclose_w();
extern void gzflush();
extern void gzfwrite();
extern void gzprintf();
extern void gzputc();
extern void gzputs();
extern void gzsetparams();
extern void gzvprintf();
extern void gzwrite();
extern void inflateBack();
extern void inflateBackEnd();
extern void inflateBackInit_();
extern void inflate_fast();
extern void inflate();
extern void inflateCodesUsed();
extern void inflateCopy();
extern void inflateEnd();
extern void inflateGetDictionary();
extern void inflateGetHeader();
extern void inflateInit2_();
extern void inflateInit_();
extern void inflateMark();
extern void inflatePrime();
extern void inflateReset();
extern void inflateReset2();
extern void inflateResetKeep();
extern void inflateSetDictionary();
extern void inflateSync();
extern void inflateSyncPoint();
extern void inflateUndermine();
extern void inflateValidate();
extern void inflate_table();
extern void _tr_align();
extern void _tr_flush_bits();
extern void _tr_flush_block();
extern void _tr_init();
extern void _tr_stored_block();
extern void _tr_tally();
extern void uncompress();
extern void uncompress2();
extern void adler32();
extern void adler32_combine();
extern void adler32_combine64();
extern void adler32_z();
extern void crc32();
extern void crc32_combine();
extern void crc32_combine64();
extern void crc32_combine_gen();
extern void crc32_combine_gen64();
extern void crc32_combine_op();
extern void crc32_z();
extern void get_crc_table();
extern void zError();
extern void zcalloc();
extern void zcfree();
extern void zlibCompileFlags();
extern void zlibVersion();
extern void Java_java_nio_MappedByteBuffer_force0();
extern void Java_java_nio_MappedByteBuffer_isLoaded0();
extern void Java_java_nio_MappedByteBuffer_load0();
extern void Java_sun_nio_ch_DatagramChannelImpl_disconnect0();
extern void Java_sun_nio_ch_DatagramChannelImpl_initIDs();
extern void Java_sun_nio_ch_DatagramChannelImpl_receive0();
extern void Java_sun_nio_ch_DatagramChannelImpl_send0();
extern void Java_sun_nio_ch_DatagramDispatcher_read0();
extern void Java_sun_nio_ch_DatagramDispatcher_readv0();
extern void Java_sun_nio_ch_DatagramDispatcher_write0();
extern void Java_sun_nio_ch_DatagramDispatcher_writev0();
extern void Java_sun_nio_ch_FileChannelImpl_close0();
extern void Java_sun_nio_ch_FileChannelImpl_initIDs();
extern void Java_sun_nio_ch_FileChannelImpl_map0();
extern void Java_sun_nio_ch_FileChannelImpl_transferTo0();
extern void Java_sun_nio_ch_FileChannelImpl_unmap0();
extern void Java_sun_nio_ch_FileDispatcherImpl_close0();
extern void Java_sun_nio_ch_FileDispatcherImpl_closeIntFD();
extern void Java_sun_nio_ch_FileDispatcherImpl_force0();
extern void Java_sun_nio_ch_FileDispatcherImpl_init();
extern void Java_sun_nio_ch_FileDispatcherImpl_lock0();
extern void Java_sun_nio_ch_FileDispatcherImpl_preClose0();
extern void Java_sun_nio_ch_FileDispatcherImpl_pread0();
extern void Java_sun_nio_ch_FileDispatcherImpl_pwrite0();
extern void Java_sun_nio_ch_FileDispatcherImpl_read0();
extern void Java_sun_nio_ch_FileDispatcherImpl_readv0();
extern void Java_sun_nio_ch_FileDispatcherImpl_release0();
extern void Java_sun_nio_ch_FileDispatcherImpl_seek0();
extern void Java_sun_nio_ch_FileDispatcherImpl_size0();
extern void Java_sun_nio_ch_FileDispatcherImpl_truncate0();
extern void Java_sun_nio_ch_FileDispatcherImpl_write0();
extern void Java_sun_nio_ch_FileDispatcherImpl_writev0();
extern void Java_sun_nio_ch_FileKey_init();
extern void Java_sun_nio_ch_FileKey_initIDs();
extern void Java_sun_nio_ch_IOUtil_configureBlocking();
extern void Java_sun_nio_ch_IOUtil_drain();
extern void Java_sun_nio_ch_IOUtil_fdLimit();
extern void Java_sun_nio_ch_IOUtil_fdVal();
extern void Java_sun_nio_ch_IOUtil_initIDs();
extern void Java_sun_nio_ch_IOUtil_iovMax();
extern void Java_sun_nio_ch_IOUtil_makePipe();
extern void Java_sun_nio_ch_IOUtil_randomBytes();
extern void Java_sun_nio_ch_IOUtil_setfdVal();
extern void convertLongReturnVal();
extern void convertReturnVal();
extern void fdval();
extern void Java_sun_nio_ch_Net_bind0();
extern void Java_sun_nio_ch_Net_blockOrUnblock4();
extern void Java_sun_nio_ch_Net_blockOrUnblock6();
extern void Java_sun_nio_ch_Net_canIPv6SocketJoinIPv4Group0();
extern void Java_sun_nio_ch_Net_canJoin6WithIPv4Group0();
extern void Java_sun_nio_ch_Net_connect0();
extern void Java_sun_nio_ch_Net_getIntOption0();
extern void Java_sun_nio_ch_Net_getInterface4();
extern void Java_sun_nio_ch_Net_getInterface6();
extern void Java_sun_nio_ch_Net_initIDs();
extern void Java_sun_nio_ch_Net_isExclusiveBindAvailable();
extern void Java_sun_nio_ch_Net_isIPv6Available0();
extern void Java_sun_nio_ch_Net_joinOrDrop4();
extern void Java_sun_nio_ch_Net_joinOrDrop6();
extern void Java_sun_nio_ch_Net_listen();
extern void Java_sun_nio_ch_Net_localInetAddress();
extern void Java_sun_nio_ch_Net_localPort();
extern void Java_sun_nio_ch_Net_poll();
extern void Java_sun_nio_ch_Net_pollconnValue();
extern void Java_sun_nio_ch_Net_pollerrValue();
extern void Java_sun_nio_ch_Net_pollhupValue();
extern void Java_sun_nio_ch_Net_pollinValue();
extern void Java_sun_nio_ch_Net_pollnvalValue();
extern void Java_sun_nio_ch_Net_polloutValue();
extern void Java_sun_nio_ch_Net_setIntOption0();
extern void Java_sun_nio_ch_Net_setInterface4();
extern void Java_sun_nio_ch_Net_setInterface6();
extern void Java_sun_nio_ch_Net_shutdown();
extern void Java_sun_nio_ch_Net_socket0();
extern void handleSocketError();
extern void Java_sun_nio_ch_ServerSocketChannelImpl_accept0();
extern void Java_sun_nio_ch_ServerSocketChannelImpl_initIDs();
extern void Java_sun_nio_ch_SocketChannelImpl_checkConnect();
extern void Java_sun_nio_ch_SocketChannelImpl_sendOutOfBandData();
extern void Java_sun_nio_ch_EPoll_close0();
extern void Java_sun_nio_ch_EPoll_dataOffset();
extern void Java_sun_nio_ch_EPoll_epollCreate();
extern void Java_sun_nio_ch_EPoll_epollCtl();
extern void Java_sun_nio_ch_EPoll_epollWait();
extern void Java_sun_nio_ch_EPoll_eventSize();
extern void Java_sun_nio_ch_EPoll_eventsOffset();
extern void Java_sun_nio_ch_EPollArrayWrapper_epollCreate();
extern void Java_sun_nio_ch_EPollArrayWrapper_epollCtl();
extern void Java_sun_nio_ch_EPollArrayWrapper_epollWait();
extern void Java_sun_nio_ch_EPollArrayWrapper_init();
extern void Java_sun_nio_ch_EPollArrayWrapper_interrupt();
extern void Java_sun_nio_ch_EPollArrayWrapper_offsetofData();
extern void Java_sun_nio_ch_EPollArrayWrapper_sizeofEPollEvent();
extern void Java_sun_nio_ch_EPollPort_close0();
extern void Java_sun_nio_ch_EPollPort_drain1();
extern void Java_sun_nio_ch_EPollPort_interrupt();
extern void Java_sun_nio_ch_EPollPort_socketpair();
extern void Java_sun_nio_ch_InheritedChannel_close0();
extern void Java_sun_nio_ch_InheritedChannel_dup();
extern void Java_sun_nio_ch_InheritedChannel_dup2();
extern void Java_sun_nio_ch_InheritedChannel_open0();
extern void Java_sun_nio_ch_InheritedChannel_peerAddress0();
extern void Java_sun_nio_ch_InheritedChannel_peerPort0();
extern void Java_sun_nio_ch_InheritedChannel_soType0();
extern void Java_sun_nio_ch_NativeThread_current();
extern void Java_sun_nio_ch_NativeThread_init();
extern void Java_sun_nio_ch_NativeThread_signal();
extern void Java_sun_nio_ch_PollArrayWrapper_interrupt();
extern void Java_sun_nio_ch_PollArrayWrapper_poll0();
extern void Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_accept0();
extern void Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_initIDs();
extern void Java_sun_nio_ch_UnixAsynchronousSocketChannelImpl_checkConnect();
extern void Java_sun_nio_fs_GnomeFileTypeDetector_initializeGio();
extern void Java_sun_nio_fs_GnomeFileTypeDetector_initializeGnomeVfs();
extern void Java_sun_nio_fs_GnomeFileTypeDetector_probeUsingGio();
extern void Java_sun_nio_fs_GnomeFileTypeDetector_probeUsingGnomeVfs();
extern void Java_sun_nio_fs_MagicFileTypeDetector_initialize0();
extern void Java_sun_nio_fs_MagicFileTypeDetector_probe0();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_endmntent();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_fgetxattr0();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_flistxattr();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_fremovexattr0();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_fsetxattr0();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_getlinelen();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_getmntent0();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_init();
extern void Java_sun_nio_fs_LinuxNativeDispatcher_setmntent0();
extern void Java_sun_nio_fs_LinuxWatchService_configureBlocking();
extern void Java_sun_nio_fs_LinuxWatchService_eventOffsets();
extern void Java_sun_nio_fs_LinuxWatchService_eventSize();
extern void Java_sun_nio_fs_LinuxWatchService_inotifyAddWatch();
extern void Java_sun_nio_fs_LinuxWatchService_inotifyInit();
extern void Java_sun_nio_fs_LinuxWatchService_inotifyRmWatch();
extern void Java_sun_nio_fs_LinuxWatchService_poll();
extern void Java_sun_nio_fs_LinuxWatchService_socketpair();
extern void Java_sun_nio_fs_UnixCopyFile_transfer();
extern void Java_sun_nio_fs_UnixNativeDispatcher_access0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_chmod0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_chown0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_close();
extern void Java_sun_nio_fs_UnixNativeDispatcher_closedir();
extern void Java_sun_nio_fs_UnixNativeDispatcher_dup();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fchmod();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fchown();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fclose();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fdopendir();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fopen0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fpathconf();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fstat();
extern void Java_sun_nio_fs_UnixNativeDispatcher_fstatat0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_futimes();
extern void Java_sun_nio_fs_UnixNativeDispatcher_getcwd();
extern void Java_sun_nio_fs_UnixNativeDispatcher_getgrgid();
extern void Java_sun_nio_fs_UnixNativeDispatcher_getgrnam0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_getpwnam0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_getpwuid();
extern void Java_sun_nio_fs_UnixNativeDispatcher_init();
extern void Java_sun_nio_fs_UnixNativeDispatcher_lchown0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_link0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_lstat0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_mkdir0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_mknod0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_open0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_openat0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_opendir0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_pathconf0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_read();
extern void Java_sun_nio_fs_UnixNativeDispatcher_readdir();
extern void Java_sun_nio_fs_UnixNativeDispatcher_readlink0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_realpath0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_rename0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_renameat0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_rewind();
extern void Java_sun_nio_fs_UnixNativeDispatcher_rmdir0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_stat0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_statvfs0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_strerror();
extern void Java_sun_nio_fs_UnixNativeDispatcher_symlink0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_unlink0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_unlinkat0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_utimes0();
extern void Java_sun_nio_fs_UnixNativeDispatcher_write();
extern void __libnio_JNI_OnLoad();
extern void __libnio_JNI_OnUnload();
extern void NET_SockaddrEqualsInetAddress();
extern void NET_SockaddrToInetAddress();
extern void __libnet_JNI_OnLoad();
extern void getInet6Address_ipaddress();
extern void getInet6Address_scopeid();
extern void getInet6Address_scopeid_set();
extern void getInet6Address_scopeifname();
extern void getInetAddress_addr();
extern void getInetAddress_family();
extern void getInetAddress_hostName();
extern void in_cksum();
extern void initInetAddressIDs();
extern void ipv6_available();
extern void setInet6Address_ipaddress();
extern void setInet6Address_scopeid();
extern void setInet6Address_scopeifname();
extern void setInetAddress_addr();
extern void setInetAddress_family();
extern void setInetAddress_hostName();
extern void Java_java_net_InetAddress_init();
extern void Java_java_net_Inet4Address_init();
extern void Java_java_net_Inet6Address_init();
extern void Java_java_net_DatagramPacket_init();
extern void IPv6_supported();
extern void NET_AllocSockaddr();
extern void NET_Bind();
extern void NET_EnableFastTcpLoopback();
extern void NET_GetCurrentTime();
extern void NET_GetFileDescriptorID();
extern void NET_GetPortFromSockaddr();
extern void NET_GetSockOpt();
extern void NET_IPv4MappedToIPv4();
extern void NET_InetAddressToSockaddr();
extern void NET_IsEqual();
extern void NET_IsIPv4Mapped();
extern void NET_IsZeroAddr();
extern void NET_MapSocketOption();
extern void NET_SetSockOpt();
extern void NET_SetTrafficClass();
extern void NET_ThrowByNameWithLastError();
extern void NET_ThrowCurrent();
extern void NET_ThrowNew();
extern void NET_Timeout();
extern void NET_TimeoutWithCurrentTime();
extern void NET_Wait();
extern void ThrowUnknownHostExceptionWithGaiError();
extern void cmpScopeID();
extern void getDefaultIPv6Interface();
extern void getDefaultScopeID();
extern void getScopeID();
extern void kernelIsV24();
extern void parseExclusiveBindProperty();
extern void platformInit();
extern void printAddr();
extern void setDefaultScopeID();
extern void Java_java_net_Inet4AddressImpl_getHostByAddr();
extern void Java_java_net_Inet4AddressImpl_getLocalHostName();
extern void Java_java_net_Inet4AddressImpl_isReachable0();
extern void Java_java_net_Inet4AddressImpl_lookupAllHostAddr();
extern void Java_java_net_Inet6AddressImpl_getHostByAddr();
extern void Java_java_net_Inet6AddressImpl_getLocalHostName();
extern void Java_java_net_Inet6AddressImpl_isReachable0();
extern void Java_java_net_Inet6AddressImpl_lookupAllHostAddr();
extern void Java_java_net_InetAddressImplFactory_isIPv6Supported();
extern void Java_java_net_NetworkInterface_getAll();
extern void Java_java_net_NetworkInterface_getByIndex0();
extern void Java_java_net_NetworkInterface_getByInetAddress0();
extern void Java_java_net_NetworkInterface_getByName0();
extern void Java_java_net_NetworkInterface_getMTU0();
extern void Java_java_net_NetworkInterface_getMacAddr0();
extern void Java_java_net_NetworkInterface_init();
extern void Java_java_net_NetworkInterface_isLoopback0();
extern void Java_java_net_NetworkInterface_isP2P0();
extern void Java_java_net_NetworkInterface_isUp0();
extern void Java_java_net_NetworkInterface_supportsMulticast0();
extern void Java_java_net_PlainDatagramSocketImpl_bind0();
extern void Java_java_net_PlainDatagramSocketImpl_connect0();
extern void Java_java_net_PlainDatagramSocketImpl_dataAvailable();
extern void Java_java_net_PlainDatagramSocketImpl_datagramSocketClose();
extern void Java_java_net_PlainDatagramSocketImpl_datagramSocketCreate();
extern void Java_java_net_PlainDatagramSocketImpl_disconnect0();
extern void Java_java_net_PlainDatagramSocketImpl_getTTL();
extern void Java_java_net_PlainDatagramSocketImpl_getTimeToLive();
extern void Java_java_net_PlainDatagramSocketImpl_init();
extern void Java_java_net_PlainDatagramSocketImpl_join();
extern void Java_java_net_PlainDatagramSocketImpl_leave();
extern void Java_java_net_PlainDatagramSocketImpl_peek();
extern void Java_java_net_PlainDatagramSocketImpl_peekData();
extern void Java_java_net_PlainDatagramSocketImpl_receive0();
extern void Java_java_net_PlainDatagramSocketImpl_send();
extern void Java_java_net_PlainDatagramSocketImpl_setTTL();
extern void Java_java_net_PlainDatagramSocketImpl_setTimeToLive();
extern void Java_java_net_PlainDatagramSocketImpl_socketGetOption();
extern void Java_java_net_PlainDatagramSocketImpl_socketSetOption0();
extern void getMulticastInterface();
extern void Java_java_net_PlainSocketImpl_initProto();
extern void Java_java_net_PlainSocketImpl_socketAccept();
extern void Java_java_net_PlainSocketImpl_socketAvailable();
extern void Java_java_net_PlainSocketImpl_socketBind();
extern void Java_java_net_PlainSocketImpl_socketClose0();
extern void Java_java_net_PlainSocketImpl_socketConnect();
extern void Java_java_net_PlainSocketImpl_socketCreate();
extern void Java_java_net_PlainSocketImpl_socketGetOption();
extern void Java_java_net_PlainSocketImpl_socketListen();
extern void Java_java_net_PlainSocketImpl_socketSendUrgentData();
extern void Java_java_net_PlainSocketImpl_socketSetOption0();
extern void Java_java_net_PlainSocketImpl_socketShutdown();
extern void Java_java_net_SocketInputStream_init();
extern void Java_java_net_SocketInputStream_socketRead0();
extern void Java_java_net_SocketOutputStream_init();
extern void Java_java_net_SocketOutputStream_socketWrite0();
extern void NET_Accept();
extern void NET_Connect();
extern void NET_Dup2();
extern void NET_NonBlockingRead();
extern void NET_Poll();
extern void NET_Read();
extern void NET_ReadV();
extern void NET_RecvFrom();
extern void NET_Send();
extern void NET_SendTo();
extern void NET_SocketClose();
extern void NET_Timeout0();
extern void NET_WriteV();

/* Symbol table for "/ikvm/bin/libiava.so" (259 symbols) */
static const jvm_symbol_entry_t _syms_libiava_so[] = {
    { "JDK_execvpe", (void*)JDK_execvpe },
    { "childProcess", (void*)childProcess },
    { "closeDescriptors", (void*)closeDescriptors },
    { "closeSafely", (void*)closeSafely },
    { "execve_as_traditional_shell_script", (void*)execve_as_traditional_shell_script },
    { "execve_with_shell_fallback", (void*)execve_with_shell_fallback },
    { "initVectorFromBlock", (void*)initVectorFromBlock },
    { "isAsciiDigit", (void*)isAsciiDigit },
    { "magicNumber", (void*)magicNumber },
    { "moveDescriptor", (void*)moveDescriptor },
    { "readFully", (void*)readFully },
    { "restartableDup2", (void*)restartableDup2 },
    { "restartableWrite", (void*)restartableWrite },
    { "GetJavaProperties", (void*)GetJavaProperties },
    { "GetStringPlatform", (void*)GetStringPlatform },
    { "Java_java_lang_ProcessEnvironment_environ", (void*)Java_java_lang_ProcessEnvironment_environ },
    { "Java_java_lang_UNIXProcess_destroyProcess", (void*)Java_java_lang_UNIXProcess_destroyProcess },
    { "Java_java_lang_UNIXProcess_forkAndExec", (void*)Java_java_lang_UNIXProcess_forkAndExec },
    { "Java_java_lang_UNIXProcess_init", (void*)Java_java_lang_UNIXProcess_init },
    { "Java_java_lang_UNIXProcess_waitForProcessExit", (void*)Java_java_lang_UNIXProcess_waitForProcessExit },
    { "Java_java_lang_Double_doubleToRawLongBits", (void*)Java_java_lang_Double_doubleToRawLongBits },
    { "Java_java_lang_Double_longBitsToDouble", (void*)Java_java_lang_Double_longBitsToDouble },
    { "Java_java_lang_Float_floatToRawIntBits", (void*)Java_java_lang_Float_floatToRawIntBits },
    { "Java_java_lang_Float_intBitsToFloat", (void*)Java_java_lang_Float_intBitsToFloat },
    { "Java_java_lang_StrictMath_IEEEremainder", (void*)Java_java_lang_StrictMath_IEEEremainder },
    { "Java_java_lang_StrictMath_acos", (void*)Java_java_lang_StrictMath_acos },
    { "Java_java_lang_StrictMath_asin", (void*)Java_java_lang_StrictMath_asin },
    { "Java_java_lang_StrictMath_atan", (void*)Java_java_lang_StrictMath_atan },
    { "Java_java_lang_StrictMath_atan2", (void*)Java_java_lang_StrictMath_atan2 },
    { "Java_java_lang_StrictMath_cbrt", (void*)Java_java_lang_StrictMath_cbrt },
    { "Java_java_lang_StrictMath_cos", (void*)Java_java_lang_StrictMath_cos },
    { "Java_java_lang_StrictMath_cosh", (void*)Java_java_lang_StrictMath_cosh },
    { "Java_java_lang_StrictMath_exp", (void*)Java_java_lang_StrictMath_exp },
    { "Java_java_lang_StrictMath_expm1", (void*)Java_java_lang_StrictMath_expm1 },
    { "Java_java_lang_StrictMath_hypot", (void*)Java_java_lang_StrictMath_hypot },
    { "Java_java_lang_StrictMath_log", (void*)Java_java_lang_StrictMath_log },
    { "Java_java_lang_StrictMath_log10", (void*)Java_java_lang_StrictMath_log10 },
    { "Java_java_lang_StrictMath_log1p", (void*)Java_java_lang_StrictMath_log1p },
    { "Java_java_lang_StrictMath_pow", (void*)Java_java_lang_StrictMath_pow },
    { "Java_java_lang_StrictMath_sin", (void*)Java_java_lang_StrictMath_sin },
    { "Java_java_lang_StrictMath_sinh", (void*)Java_java_lang_StrictMath_sinh },
    { "Java_java_lang_StrictMath_sqrt", (void*)Java_java_lang_StrictMath_sqrt },
    { "Java_java_lang_StrictMath_tan", (void*)Java_java_lang_StrictMath_tan },
    { "Java_java_lang_StrictMath_tanh", (void*)Java_java_lang_StrictMath_tanh },
    { "Java_java_lang_System_identityHashCode", (void*)Java_java_lang_System_identityHashCode },
    { "Java_java_lang_System_initProperties", (void*)Java_java_lang_System_initProperties },
    { "Java_java_lang_System_mapLibraryName", (void*)Java_java_lang_System_mapLibraryName },
    { "Java_java_lang_System_registerNatives", (void*)Java_java_lang_System_registerNatives },
    { "Java_java_lang_System_setErr0", (void*)Java_java_lang_System_setErr0 },
    { "Java_java_lang_System_setIn0", (void*)Java_java_lang_System_setIn0 },
    { "Java_java_lang_System_setOut0", (void*)Java_java_lang_System_setOut0 },
    { "fillI18nProps", (void*)fillI18nProps },
    { "Java_java_lang_reflect_Proxy_defineClass0", (void*)Java_java_lang_reflect_Proxy_defineClass0 },
    { "__j__ieee754_acos", (void*)__j__ieee754_acos },
    { "__j__ieee754_asin", (void*)__j__ieee754_asin },
    { "__j__ieee754_atan2", (void*)__j__ieee754_atan2 },
    { "__j__ieee754_atanh", (void*)__j__ieee754_atanh },
    { "__j__ieee754_cosh", (void*)__j__ieee754_cosh },
    { "__j__ieee754_exp", (void*)__j__ieee754_exp },
    { "__j__ieee754_fmod", (void*)__j__ieee754_fmod },
    { "__j__ieee754_hypot", (void*)__j__ieee754_hypot },
    { "__j__ieee754_log10", (void*)__j__ieee754_log10 },
    { "__j__ieee754_log", (void*)__j__ieee754_log },
    { "__j__ieee754_pow", (void*)__j__ieee754_pow },
    { "__j__ieee754_remainder", (void*)__j__ieee754_remainder },
    { "__j__ieee754_rem_pio2", (void*)__j__ieee754_rem_pio2 },
    { "__j__ieee754_scalb", (void*)__j__ieee754_scalb },
    { "__j__ieee754_sinh", (void*)__j__ieee754_sinh },
    { "__j__ieee754_sqrt", (void*)__j__ieee754_sqrt },
    { "__j__kernel_cos", (void*)__j__kernel_cos },
    { "__j__kernel_rem_pio2", (void*)__j__kernel_rem_pio2 },
    { "__j__kernel_sin", (void*)__j__kernel_sin },
    { "__j__kernel_standard", (void*)__j__kernel_standard },
    { "__j__kernel_tan", (void*)__j__kernel_tan },
    { "jatan", (void*)jatan },
    { "jcbrt", (void*)jcbrt },
    { "jceil", (void*)jceil },
    { "copysign", (void*)copysign },
    { "jcos", (void*)jcos },
    { "jexpm1", (void*)jexpm1 },
    { "jfabs", (void*)jfabs },
    { "finite", (void*)finite },
    { "jfloor", (void*)jfloor },
    { "frexp", (void*)frexp },
    { "ilogb", (void*)ilogb },
    { "isnan", (void*)isnan },
    { "ldexp", (void*)ldexp },
    { "jlog1p", (void*)jlog1p },
    { "logb", (void*)logb },
    { "matherr", (void*)matherr },
    { "modf", (void*)modf },
    { "nextafter", (void*)nextafter },
    { "rint", (void*)rint },
    { "scalbn", (void*)scalbn },
    { "significand", (void*)significand },
    { "jsin", (void*)jsin },
    { "jtan", (void*)jtan },
    { "jtanh", (void*)jtanh },
    { "jacos", (void*)jacos },
    { "jasin", (void*)jasin },
    { "jatan2", (void*)jatan2 },
    { "atanh", (void*)atanh },
    { "jcosh", (void*)jcosh },
    { "jexp", (void*)jexp },
    { "jmod", (void*)jmod },
    { "jhypot", (void*)jhypot },
    { "jlog10", (void*)jlog10 },
    { "jlog", (void*)jlog },
    { "jpow", (void*)jpow },
    { "jremainder", (void*)jremainder },
    { "scalb", (void*)scalb },
    { "jsinh", (void*)jsinh },
    { "jsqrt", (void*)jsqrt },
    { "Java_java_io_FileInputStream_available0", (void*)Java_java_io_FileInputStream_available0 },
    { "Java_java_io_FileInputStream_initIDs", (void*)Java_java_io_FileInputStream_initIDs },
    { "Java_java_io_FileInputStream_open0", (void*)Java_java_io_FileInputStream_open0 },
    { "Java_java_io_FileInputStream_read0", (void*)Java_java_io_FileInputStream_read0 },
    { "Java_java_io_FileInputStream_readBytes", (void*)Java_java_io_FileInputStream_readBytes },
    { "Java_java_io_FileInputStream_skip0", (void*)Java_java_io_FileInputStream_skip0 },
    { "readBytes", (void*)readBytes },
    { "readSingle", (void*)readSingle },
    { "throwFileNotFoundException", (void*)throwFileNotFoundException },
    { "writeBytes", (void*)writeBytes },
    { "writeSingle", (void*)writeSingle },
    { "Java_java_io_ObjectInputStream_bytesToDoubles", (void*)Java_java_io_ObjectInputStream_bytesToDoubles },
    { "Java_java_io_ObjectInputStream_bytesToFloats", (void*)Java_java_io_ObjectInputStream_bytesToFloats },
    { "Java_java_io_ObjectOutputStream_doublesToBytes", (void*)Java_java_io_ObjectOutputStream_doublesToBytes },
    { "Java_java_io_ObjectOutputStream_floatsToBytes", (void*)Java_java_io_ObjectOutputStream_floatsToBytes },
    { "Java_java_io_ObjectStreamClass_hasStaticInitializer", (void*)Java_java_io_ObjectStreamClass_hasStaticInitializer },
    { "Java_java_io_ObjectStreamClass_initNative", (void*)Java_java_io_ObjectStreamClass_initNative },
    { "Java_java_io_RandomAccessFile_getFilePointer", (void*)Java_java_io_RandomAccessFile_getFilePointer },
    { "Java_java_io_RandomAccessFile_initIDs", (void*)Java_java_io_RandomAccessFile_initIDs },
    { "Java_java_io_RandomAccessFile_length", (void*)Java_java_io_RandomAccessFile_length },
    { "Java_java_io_RandomAccessFile_open0", (void*)Java_java_io_RandomAccessFile_open0 },
    { "Java_java_io_RandomAccessFile_read0", (void*)Java_java_io_RandomAccessFile_read0 },
    { "Java_java_io_RandomAccessFile_readBytes", (void*)Java_java_io_RandomAccessFile_readBytes },
    { "Java_java_io_RandomAccessFile_seek0", (void*)Java_java_io_RandomAccessFile_seek0 },
    { "Java_java_io_RandomAccessFile_setLength", (void*)Java_java_io_RandomAccessFile_setLength },
    { "Java_java_io_RandomAccessFile_write0", (void*)Java_java_io_RandomAccessFile_write0 },
    { "Java_java_io_RandomAccessFile_writeBytes", (void*)Java_java_io_RandomAccessFile_writeBytes },
    { "canonicalize", (void*)canonicalize },
    { "Java_java_io_Console_echo", (void*)Java_java_io_Console_echo },
    { "Java_java_io_Console_encoding", (void*)Java_java_io_Console_encoding },
    { "Java_java_io_Console_istty", (void*)Java_java_io_Console_istty },
    { "Java_java_io_FileDescriptor_initIDs", (void*)Java_java_io_FileDescriptor_initIDs },
    { "Java_java_io_FileDescriptor_sync", (void*)Java_java_io_FileDescriptor_sync },
    { "Java_java_io_FileInputStream_close0", (void*)Java_java_io_FileInputStream_close0 },
    { "Java_java_io_FileOutputStream_close0", (void*)Java_java_io_FileOutputStream_close0 },
    { "Java_java_io_FileOutputStream_initIDs", (void*)Java_java_io_FileOutputStream_initIDs },
    { "Java_java_io_FileOutputStream_open0", (void*)Java_java_io_FileOutputStream_open0 },
    { "Java_java_io_FileOutputStream_write", (void*)Java_java_io_FileOutputStream_write },
    { "Java_java_io_FileOutputStream_writeBytes", (void*)Java_java_io_FileOutputStream_writeBytes },
    { "fileClose", (void*)fileClose },
    { "fileOpen", (void*)fileOpen },
    { "getLastErrorString", (void*)getLastErrorString },
    { "handleAvailable", (void*)handleAvailable },
    { "handleOpen", (void*)handleOpen },
    { "handleRead", (void*)handleRead },
    { "handleSetLength", (void*)handleSetLength },
    { "handleWrite", (void*)handleWrite },
    { "Java_java_io_RandomAccessFile_close0", (void*)Java_java_io_RandomAccessFile_close0 },
    { "Java_java_io_UnixFileSystem_canonicalize0", (void*)Java_java_io_UnixFileSystem_canonicalize0 },
    { "Java_java_io_UnixFileSystem_checkAccess", (void*)Java_java_io_UnixFileSystem_checkAccess },
    { "Java_java_io_UnixFileSystem_createDirectory", (void*)Java_java_io_UnixFileSystem_createDirectory },
    { "Java_java_io_UnixFileSystem_createFileExclusively", (void*)Java_java_io_UnixFileSystem_createFileExclusively },
    { "Java_java_io_UnixFileSystem_delete0", (void*)Java_java_io_UnixFileSystem_delete0 },
    { "Java_java_io_UnixFileSystem_getBooleanAttributes0", (void*)Java_java_io_UnixFileSystem_getBooleanAttributes0 },
    { "Java_java_io_UnixFileSystem_getLastModifiedTime", (void*)Java_java_io_UnixFileSystem_getLastModifiedTime },
    { "Java_java_io_UnixFileSystem_getLength", (void*)Java_java_io_UnixFileSystem_getLength },
    { "Java_java_io_UnixFileSystem_getSpace", (void*)Java_java_io_UnixFileSystem_getSpace },
    { "Java_java_io_UnixFileSystem_initIDs", (void*)Java_java_io_UnixFileSystem_initIDs },
    { "Java_java_io_UnixFileSystem_list", (void*)Java_java_io_UnixFileSystem_list },
    { "Java_java_io_UnixFileSystem_rename0", (void*)Java_java_io_UnixFileSystem_rename0 },
    { "Java_java_io_UnixFileSystem_setLastModifiedTime", (void*)Java_java_io_UnixFileSystem_setLastModifiedTime },
    { "Java_java_io_UnixFileSystem_setPermission", (void*)Java_java_io_UnixFileSystem_setPermission },
    { "Java_java_io_UnixFileSystem_setReadOnly", (void*)Java_java_io_UnixFileSystem_setReadOnly },
    { "Java_java_nio_Bits_copySwapMemory0", (void*)Java_java_nio_Bits_copySwapMemory0 },
    { "VerifyClassname", (void*)VerifyClassname },
    { "VerifyFixClassname", (void*)VerifyFixClassname },
    { "JNI_OnLoad", (void*)JNI_OnLoad },
    { "JDK_GetVersionInfo0", (void*)JDK_GetVersionInfo0 },
    { "jio_fprintf", (void*)jio_fprintf },
    { "jio_snprintf", (void*)jio_snprintf },
    { "Canonicalize", (void*)Canonicalize },
    { "GetStringPlatformChars", (void*)GetStringPlatformChars },
    { "JNU_CallMethodByName", (void*)JNU_CallMethodByName },
    { "JNU_CallMethodByNameV", (void*)JNU_CallMethodByNameV },
    { "JNU_CallStaticMethodByName", (void*)JNU_CallStaticMethodByName },
    { "JNU_ClassClass", (void*)JNU_ClassClass },
    { "JNU_ClassObject", (void*)JNU_ClassObject },
    { "JNU_ClassString", (void*)JNU_ClassString },
    { "JNU_ClassThrowable", (void*)JNU_ClassThrowable },
    { "JNU_CopyObjectArray", (void*)JNU_CopyObjectArray },
    { "JNU_Equals", (void*)JNU_Equals },
    { "JNU_GetEnv", (void*)JNU_GetEnv },
    { "JNU_GetFieldByName", (void*)JNU_GetFieldByName },
    { "JNU_GetStaticFieldByName", (void*)JNU_GetStaticFieldByName },
    { "JNU_GetStringPlatformChars", (void*)JNU_GetStringPlatformChars },
    { "JNU_IsInstanceOfByName", (void*)JNU_IsInstanceOfByName },
    { "JNU_MonitorWait", (void*)JNU_MonitorWait },
    { "JNU_NewObjectByName", (void*)JNU_NewObjectByName },
    { "JNU_NewStringPlatform", (void*)JNU_NewStringPlatform },
    { "JNU_Notify", (void*)JNU_Notify },
    { "JNU_NotifyAll", (void*)JNU_NotifyAll },
    { "JNU_PrintClass", (void*)JNU_PrintClass },
    { "JNU_PrintString", (void*)JNU_PrintString },
    { "JNU_ReleaseStringPlatformChars", (void*)JNU_ReleaseStringPlatformChars },
    { "JNU_SetFieldByName", (void*)JNU_SetFieldByName },
    { "JNU_SetStaticFieldByName", (void*)JNU_SetStaticFieldByName },
    { "JNU_ThrowArrayIndexOutOfBoundsException", (void*)JNU_ThrowArrayIndexOutOfBoundsException },
    { "JNU_ThrowByName", (void*)JNU_ThrowByName },
    { "JNU_ThrowByNameWithLastError", (void*)JNU_ThrowByNameWithLastError },
    { "JNU_ThrowByNameWithMessageAndLastError", (void*)JNU_ThrowByNameWithMessageAndLastError },
    { "JNU_ThrowClassNotFoundException", (void*)JNU_ThrowClassNotFoundException },
    { "JNU_ThrowIOException", (void*)JNU_ThrowIOException },
    { "JNU_ThrowIOExceptionWithLastError", (void*)JNU_ThrowIOExceptionWithLastError },
    { "JNU_ThrowIllegalAccessError", (void*)JNU_ThrowIllegalAccessError },
    { "JNU_ThrowIllegalAccessException", (void*)JNU_ThrowIllegalAccessException },
    { "JNU_ThrowIllegalArgumentException", (void*)JNU_ThrowIllegalArgumentException },
    { "JNU_ThrowInstantiationException", (void*)JNU_ThrowInstantiationException },
    { "JNU_ThrowInternalError", (void*)JNU_ThrowInternalError },
    { "JNU_ThrowNoSuchFieldError", (void*)JNU_ThrowNoSuchFieldError },
    { "JNU_ThrowNoSuchFieldException", (void*)JNU_ThrowNoSuchFieldException },
    { "JNU_ThrowNoSuchMethodError", (void*)JNU_ThrowNoSuchMethodError },
    { "JNU_ThrowNoSuchMethodException", (void*)JNU_ThrowNoSuchMethodException },
    { "JNU_ThrowNullPointerException", (void*)JNU_ThrowNullPointerException },
    { "JNU_ThrowNumberFormatException", (void*)JNU_ThrowNumberFormatException },
    { "JNU_ThrowOutOfMemoryError", (void*)JNU_ThrowOutOfMemoryError },
    { "JNU_ThrowStringIndexOutOfBoundsException", (void*)JNU_ThrowStringIndexOutOfBoundsException },
    { "JNU_ToString", (void*)JNU_ToString },
    { "NewStringPlatform", (void*)NewStringPlatform },
    { "getFastEncoding", (void*)getFastEncoding },
    { "initializeEncoding", (void*)initializeEncoding },
    { "Java_sun_misc_MessageUtils_toStderr", (void*)Java_sun_misc_MessageUtils_toStderr },
    { "Java_sun_misc_MessageUtils_toStdout", (void*)Java_sun_misc_MessageUtils_toStdout },
    { "Java_sun_misc_NativeSignalHandler_handle0", (void*)Java_sun_misc_NativeSignalHandler_handle0 },
    { "Java_sun_misc_Version_getJdkSpecialVersion", (void*)Java_sun_misc_Version_getJdkSpecialVersion },
    { "Java_sun_misc_Version_getJdkVersionInfo", (void*)Java_sun_misc_Version_getJdkVersionInfo },
    { "Java_sun_misc_Version_getJvmSpecialVersion", (void*)Java_sun_misc_Version_getJvmSpecialVersion },
    { "Java_sun_misc_Version_getJvmVersionInfo", (void*)Java_sun_misc_Version_getJvmVersionInfo },
    { "Java_sun_misc_VMSupport_getVMTemporaryDirectory", (void*)Java_sun_misc_VMSupport_getVMTemporaryDirectory },
    { "Java_sun_misc_VMSupport_initAgentProperties", (void*)Java_sun_misc_VMSupport_initAgentProperties },
    { "Java_java_util_TimeZone_getSystemGMTOffsetID", (void*)Java_java_util_TimeZone_getSystemGMTOffsetID },
    { "Java_java_util_TimeZone_getSystemTimeZoneID", (void*)Java_java_util_TimeZone_getSystemTimeZoneID },
    { "JDK_FindJvmEntry", (void*)JDK_FindJvmEntry },
    { "JDK_InitJvmHandle", (void*)JDK_InitJvmHandle },
    { "buildJniFunctionName", (void*)buildJniFunctionName },
    { "getErrorString", (void*)getErrorString },
    { "getProcessHandle", (void*)getProcessHandle },
    { "nativeGetStringPlatformChars", (void*)nativeGetStringPlatformChars },
    { "nativeNewStringPlatform", (void*)nativeNewStringPlatform },
    { "Java_java_util_prefs_FileSystemPreferences_chmod", (void*)Java_java_util_prefs_FileSystemPreferences_chmod },
    { "Java_java_util_prefs_FileSystemPreferences_lockFile0", (void*)Java_java_util_prefs_FileSystemPreferences_lockFile0 },
    { "Java_java_util_prefs_FileSystemPreferences_unlockFile0", (void*)Java_java_util_prefs_FileSystemPreferences_unlockFile0 },
    { "Java_java_util_logging_FileHandler_isSetUID", (void*)Java_java_util_logging_FileHandler_isSetUID },
    { "findJavaTZ_md", (void*)findJavaTZ_md },
    { "getGMTOffsetID", (void*)getGMTOffsetID },
    { "Java_jdk_internal_platform_CgroupMetrics_getTotalMemorySize0", (void*)Java_jdk_internal_platform_CgroupMetrics_getTotalMemorySize0 },
    { "Java_jdk_internal_platform_CgroupMetrics_isUseContainerSupport", (void*)Java_jdk_internal_platform_CgroupMetrics_isUseContainerSupport },
    { NULL, NULL }  /* sentinel */
};

/* Symbol table for "/ikvm/bin/libzip.so" (139 symbols) */
static const jvm_symbol_entry_t _syms_libzip_so[] = {
    { "Java_java_util_zip_Adler32_update", (void*)Java_java_util_zip_Adler32_update },
    { "Java_java_util_zip_Adler32_updateByteBuffer", (void*)Java_java_util_zip_Adler32_updateByteBuffer },
    { "Java_java_util_zip_Adler32_updateBytes", (void*)Java_java_util_zip_Adler32_updateBytes },
    { "Java_java_util_zip_CRC32_update", (void*)Java_java_util_zip_CRC32_update },
    { "Java_java_util_zip_CRC32_updateByteBuffer", (void*)Java_java_util_zip_CRC32_updateByteBuffer },
    { "Java_java_util_zip_CRC32_updateBytes", (void*)Java_java_util_zip_CRC32_updateBytes },
    { "ZIP_CRC32", (void*)ZIP_CRC32 },
    { "Java_java_util_zip_Deflater_deflateBytes", (void*)Java_java_util_zip_Deflater_deflateBytes },
    { "Java_java_util_zip_Deflater_end", (void*)Java_java_util_zip_Deflater_end },
    { "Java_java_util_zip_Deflater_getAdler", (void*)Java_java_util_zip_Deflater_getAdler },
    { "Java_java_util_zip_Deflater_init", (void*)Java_java_util_zip_Deflater_init },
    { "Java_java_util_zip_Deflater_initIDs", (void*)Java_java_util_zip_Deflater_initIDs },
    { "Java_java_util_zip_Deflater_reset", (void*)Java_java_util_zip_Deflater_reset },
    { "Java_java_util_zip_Deflater_setDictionary", (void*)Java_java_util_zip_Deflater_setDictionary },
    { "Java_java_util_zip_Inflater_end", (void*)Java_java_util_zip_Inflater_end },
    { "Java_java_util_zip_Inflater_getAdler", (void*)Java_java_util_zip_Inflater_getAdler },
    { "Java_java_util_zip_Inflater_inflateBytes", (void*)Java_java_util_zip_Inflater_inflateBytes },
    { "Java_java_util_zip_Inflater_init", (void*)Java_java_util_zip_Inflater_init },
    { "Java_java_util_zip_Inflater_initIDs", (void*)Java_java_util_zip_Inflater_initIDs },
    { "Java_java_util_zip_Inflater_reset", (void*)Java_java_util_zip_Inflater_reset },
    { "Java_java_util_zip_Inflater_setDictionary", (void*)Java_java_util_zip_Inflater_setDictionary },
    { "InflateFully", (void*)InflateFully },
    { "ZIP_Close", (void*)ZIP_Close },
    { "ZIP_FindEntry", (void*)ZIP_FindEntry },
    { "ZIP_FreeEntry", (void*)ZIP_FreeEntry },
    { "ZIP_GetEntry", (void*)ZIP_GetEntry },
    { "ZIP_GetEntry2", (void*)ZIP_GetEntry2 },
    { "ZIP_GetEntryDataOffset", (void*)ZIP_GetEntryDataOffset },
    { "ZIP_GetNextEntry", (void*)ZIP_GetNextEntry },
    { "ZIP_Get_From_Cache", (void*)ZIP_Get_From_Cache },
    { "ZIP_Lock", (void*)ZIP_Lock },
    { "ZIP_Open", (void*)ZIP_Open },
    { "ZIP_Open_Generic", (void*)ZIP_Open_Generic },
    { "ZIP_Put_In_Cache", (void*)ZIP_Put_In_Cache },
    { "ZIP_Put_In_Cache0", (void*)ZIP_Put_In_Cache0 },
    { "ZIP_Read", (void*)ZIP_Read },
    { "ZIP_ReadEntry", (void*)ZIP_ReadEntry },
    { "ZIP_Unlock", (void*)ZIP_Unlock },
    { "equals", (void*)equals },
    { "compress", (void*)compress },
    { "compress2", (void*)compress2 },
    { "compressBound", (void*)compressBound },
    { "deflate", (void*)deflate },
    { "deflateBound", (void*)deflateBound },
    { "deflateCopy", (void*)deflateCopy },
    { "deflateEnd", (void*)deflateEnd },
    { "deflateGetDictionary", (void*)deflateGetDictionary },
    { "deflateInit2_", (void*)deflateInit2_ },
    { "deflateInit_", (void*)deflateInit_ },
    { "deflateParams", (void*)deflateParams },
    { "deflatePending", (void*)deflatePending },
    { "deflatePrime", (void*)deflatePrime },
    { "deflateReset", (void*)deflateReset },
    { "deflateResetKeep", (void*)deflateResetKeep },
    { "deflateSetDictionary", (void*)deflateSetDictionary },
    { "deflateSetHeader", (void*)deflateSetHeader },
    { "deflateTune", (void*)deflateTune },
    { "gzclose", (void*)gzclose },
    { "gz_error", (void*)gz_error },
    { "gz_intmax", (void*)gz_intmax },
    { "gzbuffer", (void*)gzbuffer },
    { "gzclearerr", (void*)gzclearerr },
    { "gzdopen", (void*)gzdopen },
    { "gzeof", (void*)gzeof },
    { "gzerror", (void*)gzerror },
    { "gzoffset", (void*)gzoffset },
    { "gzoffset64", (void*)gzoffset64 },
    { "gzopen", (void*)gzopen },
    { "gzopen64", (void*)gzopen64 },
    { "gzrewind", (void*)gzrewind },
    { "gzseek", (void*)gzseek },
    { "gzseek64", (void*)gzseek64 },
    { "gztell", (void*)gztell },
    { "gztell64", (void*)gztell64 },
    { "gzclose_r", (void*)gzclose_r },
    { "gzdirect", (void*)gzdirect },
    { "gzfread", (void*)gzfread },
    { "gzgetc", (void*)gzgetc },
    { "gzgetc_", (void*)gzgetc_ },
    { "gzgets", (void*)gzgets },
    { "gzread", (void*)gzread },
    { "gzungetc", (void*)gzungetc },
    { "gzclose_w", (void*)gzclose_w },
    { "gzflush", (void*)gzflush },
    { "gzfwrite", (void*)gzfwrite },
    { "gzprintf", (void*)gzprintf },
    { "gzputc", (void*)gzputc },
    { "gzputs", (void*)gzputs },
    { "gzsetparams", (void*)gzsetparams },
    { "gzvprintf", (void*)gzvprintf },
    { "gzwrite", (void*)gzwrite },
    { "inflateBack", (void*)inflateBack },
    { "inflateBackEnd", (void*)inflateBackEnd },
    { "inflateBackInit_", (void*)inflateBackInit_ },
    { "inflate_fast", (void*)inflate_fast },
    { "inflate", (void*)inflate },
    { "inflateCodesUsed", (void*)inflateCodesUsed },
    { "inflateCopy", (void*)inflateCopy },
    { "inflateEnd", (void*)inflateEnd },
    { "inflateGetDictionary", (void*)inflateGetDictionary },
    { "inflateGetHeader", (void*)inflateGetHeader },
    { "inflateInit2_", (void*)inflateInit2_ },
    { "inflateInit_", (void*)inflateInit_ },
    { "inflateMark", (void*)inflateMark },
    { "inflatePrime", (void*)inflatePrime },
    { "inflateReset", (void*)inflateReset },
    { "inflateReset2", (void*)inflateReset2 },
    { "inflateResetKeep", (void*)inflateResetKeep },
    { "inflateSetDictionary", (void*)inflateSetDictionary },
    { "inflateSync", (void*)inflateSync },
    { "inflateSyncPoint", (void*)inflateSyncPoint },
    { "inflateUndermine", (void*)inflateUndermine },
    { "inflateValidate", (void*)inflateValidate },
    { "inflate_table", (void*)inflate_table },
    { "_tr_align", (void*)_tr_align },
    { "_tr_flush_bits", (void*)_tr_flush_bits },
    { "_tr_flush_block", (void*)_tr_flush_block },
    { "_tr_init", (void*)_tr_init },
    { "_tr_stored_block", (void*)_tr_stored_block },
    { "_tr_tally", (void*)_tr_tally },
    { "uncompress", (void*)uncompress },
    { "uncompress2", (void*)uncompress2 },
    { "adler32", (void*)adler32 },
    { "adler32_combine", (void*)adler32_combine },
    { "adler32_combine64", (void*)adler32_combine64 },
    { "adler32_z", (void*)adler32_z },
    { "crc32", (void*)crc32 },
    { "crc32_combine", (void*)crc32_combine },
    { "crc32_combine64", (void*)crc32_combine64 },
    { "crc32_combine_gen", (void*)crc32_combine_gen },
    { "crc32_combine_gen64", (void*)crc32_combine_gen64 },
    { "crc32_combine_op", (void*)crc32_combine_op },
    { "crc32_z", (void*)crc32_z },
    { "get_crc_table", (void*)get_crc_table },
    { "zError", (void*)zError },
    { "zcalloc", (void*)zcalloc },
    { "zcfree", (void*)zcfree },
    { "zlibCompileFlags", (void*)zlibCompileFlags },
    { "zlibVersion", (void*)zlibVersion },
    { NULL, NULL }  /* sentinel */
};

/* Symbol table for "/ikvm/bin/libnio.so" (185 symbols) */
static const jvm_symbol_entry_t _syms_libnio_so[] = {
    { "Java_java_nio_MappedByteBuffer_force0", (void*)Java_java_nio_MappedByteBuffer_force0 },
    { "Java_java_nio_MappedByteBuffer_isLoaded0", (void*)Java_java_nio_MappedByteBuffer_isLoaded0 },
    { "Java_java_nio_MappedByteBuffer_load0", (void*)Java_java_nio_MappedByteBuffer_load0 },
    { "Java_sun_nio_ch_DatagramChannelImpl_disconnect0", (void*)Java_sun_nio_ch_DatagramChannelImpl_disconnect0 },
    { "Java_sun_nio_ch_DatagramChannelImpl_initIDs", (void*)Java_sun_nio_ch_DatagramChannelImpl_initIDs },
    { "Java_sun_nio_ch_DatagramChannelImpl_receive0", (void*)Java_sun_nio_ch_DatagramChannelImpl_receive0 },
    { "Java_sun_nio_ch_DatagramChannelImpl_send0", (void*)Java_sun_nio_ch_DatagramChannelImpl_send0 },
    { "Java_sun_nio_ch_DatagramDispatcher_read0", (void*)Java_sun_nio_ch_DatagramDispatcher_read0 },
    { "Java_sun_nio_ch_DatagramDispatcher_readv0", (void*)Java_sun_nio_ch_DatagramDispatcher_readv0 },
    { "Java_sun_nio_ch_DatagramDispatcher_write0", (void*)Java_sun_nio_ch_DatagramDispatcher_write0 },
    { "Java_sun_nio_ch_DatagramDispatcher_writev0", (void*)Java_sun_nio_ch_DatagramDispatcher_writev0 },
    { "Java_sun_nio_ch_FileChannelImpl_close0", (void*)Java_sun_nio_ch_FileChannelImpl_close0 },
    { "Java_sun_nio_ch_FileChannelImpl_initIDs", (void*)Java_sun_nio_ch_FileChannelImpl_initIDs },
    { "Java_sun_nio_ch_FileChannelImpl_map0", (void*)Java_sun_nio_ch_FileChannelImpl_map0 },
    { "Java_sun_nio_ch_FileChannelImpl_transferTo0", (void*)Java_sun_nio_ch_FileChannelImpl_transferTo0 },
    { "Java_sun_nio_ch_FileChannelImpl_unmap0", (void*)Java_sun_nio_ch_FileChannelImpl_unmap0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_close0", (void*)Java_sun_nio_ch_FileDispatcherImpl_close0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_closeIntFD", (void*)Java_sun_nio_ch_FileDispatcherImpl_closeIntFD },
    { "Java_sun_nio_ch_FileDispatcherImpl_force0", (void*)Java_sun_nio_ch_FileDispatcherImpl_force0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_init", (void*)Java_sun_nio_ch_FileDispatcherImpl_init },
    { "Java_sun_nio_ch_FileDispatcherImpl_lock0", (void*)Java_sun_nio_ch_FileDispatcherImpl_lock0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_preClose0", (void*)Java_sun_nio_ch_FileDispatcherImpl_preClose0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_pread0", (void*)Java_sun_nio_ch_FileDispatcherImpl_pread0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_pwrite0", (void*)Java_sun_nio_ch_FileDispatcherImpl_pwrite0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_read0", (void*)Java_sun_nio_ch_FileDispatcherImpl_read0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_readv0", (void*)Java_sun_nio_ch_FileDispatcherImpl_readv0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_release0", (void*)Java_sun_nio_ch_FileDispatcherImpl_release0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_seek0", (void*)Java_sun_nio_ch_FileDispatcherImpl_seek0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_size0", (void*)Java_sun_nio_ch_FileDispatcherImpl_size0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_truncate0", (void*)Java_sun_nio_ch_FileDispatcherImpl_truncate0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_write0", (void*)Java_sun_nio_ch_FileDispatcherImpl_write0 },
    { "Java_sun_nio_ch_FileDispatcherImpl_writev0", (void*)Java_sun_nio_ch_FileDispatcherImpl_writev0 },
    { "Java_sun_nio_ch_FileKey_init", (void*)Java_sun_nio_ch_FileKey_init },
    { "Java_sun_nio_ch_FileKey_initIDs", (void*)Java_sun_nio_ch_FileKey_initIDs },
    { "Java_sun_nio_ch_IOUtil_configureBlocking", (void*)Java_sun_nio_ch_IOUtil_configureBlocking },
    { "Java_sun_nio_ch_IOUtil_drain", (void*)Java_sun_nio_ch_IOUtil_drain },
    { "Java_sun_nio_ch_IOUtil_fdLimit", (void*)Java_sun_nio_ch_IOUtil_fdLimit },
    { "Java_sun_nio_ch_IOUtil_fdVal", (void*)Java_sun_nio_ch_IOUtil_fdVal },
    { "Java_sun_nio_ch_IOUtil_initIDs", (void*)Java_sun_nio_ch_IOUtil_initIDs },
    { "Java_sun_nio_ch_IOUtil_iovMax", (void*)Java_sun_nio_ch_IOUtil_iovMax },
    { "Java_sun_nio_ch_IOUtil_makePipe", (void*)Java_sun_nio_ch_IOUtil_makePipe },
    { "Java_sun_nio_ch_IOUtil_randomBytes", (void*)Java_sun_nio_ch_IOUtil_randomBytes },
    { "Java_sun_nio_ch_IOUtil_setfdVal", (void*)Java_sun_nio_ch_IOUtil_setfdVal },
    { "convertLongReturnVal", (void*)convertLongReturnVal },
    { "convertReturnVal", (void*)convertReturnVal },
    { "fdval", (void*)fdval },
    { "Java_sun_nio_ch_Net_bind0", (void*)Java_sun_nio_ch_Net_bind0 },
    { "Java_sun_nio_ch_Net_blockOrUnblock4", (void*)Java_sun_nio_ch_Net_blockOrUnblock4 },
    { "Java_sun_nio_ch_Net_blockOrUnblock6", (void*)Java_sun_nio_ch_Net_blockOrUnblock6 },
    { "Java_sun_nio_ch_Net_canIPv6SocketJoinIPv4Group0", (void*)Java_sun_nio_ch_Net_canIPv6SocketJoinIPv4Group0 },
    { "Java_sun_nio_ch_Net_canJoin6WithIPv4Group0", (void*)Java_sun_nio_ch_Net_canJoin6WithIPv4Group0 },
    { "Java_sun_nio_ch_Net_connect0", (void*)Java_sun_nio_ch_Net_connect0 },
    { "Java_sun_nio_ch_Net_getIntOption0", (void*)Java_sun_nio_ch_Net_getIntOption0 },
    { "Java_sun_nio_ch_Net_getInterface4", (void*)Java_sun_nio_ch_Net_getInterface4 },
    { "Java_sun_nio_ch_Net_getInterface6", (void*)Java_sun_nio_ch_Net_getInterface6 },
    { "Java_sun_nio_ch_Net_initIDs", (void*)Java_sun_nio_ch_Net_initIDs },
    { "Java_sun_nio_ch_Net_isExclusiveBindAvailable", (void*)Java_sun_nio_ch_Net_isExclusiveBindAvailable },
    { "Java_sun_nio_ch_Net_isIPv6Available0", (void*)Java_sun_nio_ch_Net_isIPv6Available0 },
    { "Java_sun_nio_ch_Net_joinOrDrop4", (void*)Java_sun_nio_ch_Net_joinOrDrop4 },
    { "Java_sun_nio_ch_Net_joinOrDrop6", (void*)Java_sun_nio_ch_Net_joinOrDrop6 },
    { "Java_sun_nio_ch_Net_listen", (void*)Java_sun_nio_ch_Net_listen },
    { "Java_sun_nio_ch_Net_localInetAddress", (void*)Java_sun_nio_ch_Net_localInetAddress },
    { "Java_sun_nio_ch_Net_localPort", (void*)Java_sun_nio_ch_Net_localPort },
    { "Java_sun_nio_ch_Net_poll", (void*)Java_sun_nio_ch_Net_poll },
    { "Java_sun_nio_ch_Net_pollconnValue", (void*)Java_sun_nio_ch_Net_pollconnValue },
    { "Java_sun_nio_ch_Net_pollerrValue", (void*)Java_sun_nio_ch_Net_pollerrValue },
    { "Java_sun_nio_ch_Net_pollhupValue", (void*)Java_sun_nio_ch_Net_pollhupValue },
    { "Java_sun_nio_ch_Net_pollinValue", (void*)Java_sun_nio_ch_Net_pollinValue },
    { "Java_sun_nio_ch_Net_pollnvalValue", (void*)Java_sun_nio_ch_Net_pollnvalValue },
    { "Java_sun_nio_ch_Net_polloutValue", (void*)Java_sun_nio_ch_Net_polloutValue },
    { "Java_sun_nio_ch_Net_setIntOption0", (void*)Java_sun_nio_ch_Net_setIntOption0 },
    { "Java_sun_nio_ch_Net_setInterface4", (void*)Java_sun_nio_ch_Net_setInterface4 },
    { "Java_sun_nio_ch_Net_setInterface6", (void*)Java_sun_nio_ch_Net_setInterface6 },
    { "Java_sun_nio_ch_Net_shutdown", (void*)Java_sun_nio_ch_Net_shutdown },
    { "Java_sun_nio_ch_Net_socket0", (void*)Java_sun_nio_ch_Net_socket0 },
    { "handleSocketError", (void*)handleSocketError },
    { "Java_sun_nio_ch_ServerSocketChannelImpl_accept0", (void*)Java_sun_nio_ch_ServerSocketChannelImpl_accept0 },
    { "Java_sun_nio_ch_ServerSocketChannelImpl_initIDs", (void*)Java_sun_nio_ch_ServerSocketChannelImpl_initIDs },
    { "Java_sun_nio_ch_SocketChannelImpl_checkConnect", (void*)Java_sun_nio_ch_SocketChannelImpl_checkConnect },
    { "Java_sun_nio_ch_SocketChannelImpl_sendOutOfBandData", (void*)Java_sun_nio_ch_SocketChannelImpl_sendOutOfBandData },
    { "Java_sun_nio_ch_EPoll_close0", (void*)Java_sun_nio_ch_EPoll_close0 },
    { "Java_sun_nio_ch_EPoll_dataOffset", (void*)Java_sun_nio_ch_EPoll_dataOffset },
    { "Java_sun_nio_ch_EPoll_epollCreate", (void*)Java_sun_nio_ch_EPoll_epollCreate },
    { "Java_sun_nio_ch_EPoll_epollCtl", (void*)Java_sun_nio_ch_EPoll_epollCtl },
    { "Java_sun_nio_ch_EPoll_epollWait", (void*)Java_sun_nio_ch_EPoll_epollWait },
    { "Java_sun_nio_ch_EPoll_eventSize", (void*)Java_sun_nio_ch_EPoll_eventSize },
    { "Java_sun_nio_ch_EPoll_eventsOffset", (void*)Java_sun_nio_ch_EPoll_eventsOffset },
    { "Java_sun_nio_ch_EPollArrayWrapper_epollCreate", (void*)Java_sun_nio_ch_EPollArrayWrapper_epollCreate },
    { "Java_sun_nio_ch_EPollArrayWrapper_epollCtl", (void*)Java_sun_nio_ch_EPollArrayWrapper_epollCtl },
    { "Java_sun_nio_ch_EPollArrayWrapper_epollWait", (void*)Java_sun_nio_ch_EPollArrayWrapper_epollWait },
    { "Java_sun_nio_ch_EPollArrayWrapper_init", (void*)Java_sun_nio_ch_EPollArrayWrapper_init },
    { "Java_sun_nio_ch_EPollArrayWrapper_interrupt", (void*)Java_sun_nio_ch_EPollArrayWrapper_interrupt },
    { "Java_sun_nio_ch_EPollArrayWrapper_offsetofData", (void*)Java_sun_nio_ch_EPollArrayWrapper_offsetofData },
    { "Java_sun_nio_ch_EPollArrayWrapper_sizeofEPollEvent", (void*)Java_sun_nio_ch_EPollArrayWrapper_sizeofEPollEvent },
    { "Java_sun_nio_ch_EPollPort_close0", (void*)Java_sun_nio_ch_EPollPort_close0 },
    { "Java_sun_nio_ch_EPollPort_drain1", (void*)Java_sun_nio_ch_EPollPort_drain1 },
    { "Java_sun_nio_ch_EPollPort_interrupt", (void*)Java_sun_nio_ch_EPollPort_interrupt },
    { "Java_sun_nio_ch_EPollPort_socketpair", (void*)Java_sun_nio_ch_EPollPort_socketpair },
    { "Java_sun_nio_ch_InheritedChannel_close0", (void*)Java_sun_nio_ch_InheritedChannel_close0 },
    { "Java_sun_nio_ch_InheritedChannel_dup", (void*)Java_sun_nio_ch_InheritedChannel_dup },
    { "Java_sun_nio_ch_InheritedChannel_dup2", (void*)Java_sun_nio_ch_InheritedChannel_dup2 },
    { "Java_sun_nio_ch_InheritedChannel_open0", (void*)Java_sun_nio_ch_InheritedChannel_open0 },
    { "Java_sun_nio_ch_InheritedChannel_peerAddress0", (void*)Java_sun_nio_ch_InheritedChannel_peerAddress0 },
    { "Java_sun_nio_ch_InheritedChannel_peerPort0", (void*)Java_sun_nio_ch_InheritedChannel_peerPort0 },
    { "Java_sun_nio_ch_InheritedChannel_soType0", (void*)Java_sun_nio_ch_InheritedChannel_soType0 },
    { "Java_sun_nio_ch_NativeThread_current", (void*)Java_sun_nio_ch_NativeThread_current },
    { "Java_sun_nio_ch_NativeThread_init", (void*)Java_sun_nio_ch_NativeThread_init },
    { "Java_sun_nio_ch_NativeThread_signal", (void*)Java_sun_nio_ch_NativeThread_signal },
    { "Java_sun_nio_ch_PollArrayWrapper_interrupt", (void*)Java_sun_nio_ch_PollArrayWrapper_interrupt },
    { "Java_sun_nio_ch_PollArrayWrapper_poll0", (void*)Java_sun_nio_ch_PollArrayWrapper_poll0 },
    { "Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_accept0", (void*)Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_accept0 },
    { "Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_initIDs", (void*)Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_initIDs },
    { "Java_sun_nio_ch_UnixAsynchronousSocketChannelImpl_checkConnect", (void*)Java_sun_nio_ch_UnixAsynchronousSocketChannelImpl_checkConnect },
    { "Java_sun_nio_fs_GnomeFileTypeDetector_initializeGio", (void*)Java_sun_nio_fs_GnomeFileTypeDetector_initializeGio },
    { "Java_sun_nio_fs_GnomeFileTypeDetector_initializeGnomeVfs", (void*)Java_sun_nio_fs_GnomeFileTypeDetector_initializeGnomeVfs },
    { "Java_sun_nio_fs_GnomeFileTypeDetector_probeUsingGio", (void*)Java_sun_nio_fs_GnomeFileTypeDetector_probeUsingGio },
    { "Java_sun_nio_fs_GnomeFileTypeDetector_probeUsingGnomeVfs", (void*)Java_sun_nio_fs_GnomeFileTypeDetector_probeUsingGnomeVfs },
    { "Java_sun_nio_fs_MagicFileTypeDetector_initialize0", (void*)Java_sun_nio_fs_MagicFileTypeDetector_initialize0 },
    { "Java_sun_nio_fs_MagicFileTypeDetector_probe0", (void*)Java_sun_nio_fs_MagicFileTypeDetector_probe0 },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_endmntent", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_endmntent },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_fgetxattr0", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_fgetxattr0 },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_flistxattr", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_flistxattr },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_fremovexattr0", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_fremovexattr0 },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_fsetxattr0", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_fsetxattr0 },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_getlinelen", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_getlinelen },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_getmntent0", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_getmntent0 },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_init", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_init },
    { "Java_sun_nio_fs_LinuxNativeDispatcher_setmntent0", (void*)Java_sun_nio_fs_LinuxNativeDispatcher_setmntent0 },
    { "Java_sun_nio_fs_LinuxWatchService_configureBlocking", (void*)Java_sun_nio_fs_LinuxWatchService_configureBlocking },
    { "Java_sun_nio_fs_LinuxWatchService_eventOffsets", (void*)Java_sun_nio_fs_LinuxWatchService_eventOffsets },
    { "Java_sun_nio_fs_LinuxWatchService_eventSize", (void*)Java_sun_nio_fs_LinuxWatchService_eventSize },
    { "Java_sun_nio_fs_LinuxWatchService_inotifyAddWatch", (void*)Java_sun_nio_fs_LinuxWatchService_inotifyAddWatch },
    { "Java_sun_nio_fs_LinuxWatchService_inotifyInit", (void*)Java_sun_nio_fs_LinuxWatchService_inotifyInit },
    { "Java_sun_nio_fs_LinuxWatchService_inotifyRmWatch", (void*)Java_sun_nio_fs_LinuxWatchService_inotifyRmWatch },
    { "Java_sun_nio_fs_LinuxWatchService_poll", (void*)Java_sun_nio_fs_LinuxWatchService_poll },
    { "Java_sun_nio_fs_LinuxWatchService_socketpair", (void*)Java_sun_nio_fs_LinuxWatchService_socketpair },
    { "Java_sun_nio_fs_UnixCopyFile_transfer", (void*)Java_sun_nio_fs_UnixCopyFile_transfer },
    { "Java_sun_nio_fs_UnixNativeDispatcher_access0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_access0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_chmod0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_chmod0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_chown0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_chown0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_close", (void*)Java_sun_nio_fs_UnixNativeDispatcher_close },
    { "Java_sun_nio_fs_UnixNativeDispatcher_closedir", (void*)Java_sun_nio_fs_UnixNativeDispatcher_closedir },
    { "Java_sun_nio_fs_UnixNativeDispatcher_dup", (void*)Java_sun_nio_fs_UnixNativeDispatcher_dup },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fchmod", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fchmod },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fchown", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fchown },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fclose", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fclose },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fdopendir", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fdopendir },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fopen0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fopen0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fpathconf", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fpathconf },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fstat", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fstat },
    { "Java_sun_nio_fs_UnixNativeDispatcher_fstatat0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_fstatat0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_futimes", (void*)Java_sun_nio_fs_UnixNativeDispatcher_futimes },
    { "Java_sun_nio_fs_UnixNativeDispatcher_getcwd", (void*)Java_sun_nio_fs_UnixNativeDispatcher_getcwd },
    { "Java_sun_nio_fs_UnixNativeDispatcher_getgrgid", (void*)Java_sun_nio_fs_UnixNativeDispatcher_getgrgid },
    { "Java_sun_nio_fs_UnixNativeDispatcher_getgrnam0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_getgrnam0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_getpwnam0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_getpwnam0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_getpwuid", (void*)Java_sun_nio_fs_UnixNativeDispatcher_getpwuid },
    { "Java_sun_nio_fs_UnixNativeDispatcher_init", (void*)Java_sun_nio_fs_UnixNativeDispatcher_init },
    { "Java_sun_nio_fs_UnixNativeDispatcher_lchown0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_lchown0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_link0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_link0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_lstat0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_lstat0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_mkdir0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_mkdir0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_mknod0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_mknod0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_open0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_open0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_openat0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_openat0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_opendir0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_opendir0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_pathconf0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_pathconf0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_read", (void*)Java_sun_nio_fs_UnixNativeDispatcher_read },
    { "Java_sun_nio_fs_UnixNativeDispatcher_readdir", (void*)Java_sun_nio_fs_UnixNativeDispatcher_readdir },
    { "Java_sun_nio_fs_UnixNativeDispatcher_readlink0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_readlink0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_realpath0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_realpath0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_rename0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_rename0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_renameat0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_renameat0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_rewind", (void*)Java_sun_nio_fs_UnixNativeDispatcher_rewind },
    { "Java_sun_nio_fs_UnixNativeDispatcher_rmdir0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_rmdir0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_stat0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_stat0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_statvfs0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_statvfs0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_strerror", (void*)Java_sun_nio_fs_UnixNativeDispatcher_strerror },
    { "Java_sun_nio_fs_UnixNativeDispatcher_symlink0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_symlink0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_unlink0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_unlink0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_unlinkat0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_unlinkat0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_utimes0", (void*)Java_sun_nio_fs_UnixNativeDispatcher_utimes0 },
    { "Java_sun_nio_fs_UnixNativeDispatcher_write", (void*)Java_sun_nio_fs_UnixNativeDispatcher_write },
    { "JNI_OnLoad", (void*)__libnio_JNI_OnLoad },
    { "__libnio_JNI_OnUnload", (void*)__libnio_JNI_OnUnload },
    { NULL, NULL }  /* sentinel */
};

/* Symbol table for "/ikvm/vin/libnet.so" (124 symbols) */
static const jvm_symbol_entry_t _syms_libnet_so[] = {
    { "NET_SockaddrEqualsInetAddress", (void*)NET_SockaddrEqualsInetAddress },
    { "NET_SockaddrToInetAddress", (void*)NET_SockaddrToInetAddress },
    { "JNI_OnLoad", (void*)__libnet_JNI_OnLoad },
    { "getInet6Address_ipaddress", (void*)getInet6Address_ipaddress },
    { "getInet6Address_scopeid", (void*)getInet6Address_scopeid },
    { "getInet6Address_scopeid_set", (void*)getInet6Address_scopeid_set },
    { "getInet6Address_scopeifname", (void*)getInet6Address_scopeifname },
    { "getInetAddress_addr", (void*)getInetAddress_addr },
    { "getInetAddress_family", (void*)getInetAddress_family },
    { "getInetAddress_hostName", (void*)getInetAddress_hostName },
    { "in_cksum", (void*)in_cksum },
    { "initInetAddressIDs", (void*)initInetAddressIDs },
    { "ipv6_available", (void*)ipv6_available },
    { "setInet6Address_ipaddress", (void*)setInet6Address_ipaddress },
    { "setInet6Address_scopeid", (void*)setInet6Address_scopeid },
    { "setInet6Address_scopeifname", (void*)setInet6Address_scopeifname },
    { "setInetAddress_addr", (void*)setInetAddress_addr },
    { "setInetAddress_family", (void*)setInetAddress_family },
    { "setInetAddress_hostName", (void*)setInetAddress_hostName },
    { "Java_java_net_InetAddress_init", (void*)Java_java_net_InetAddress_init },
    { "Java_java_net_Inet4Address_init", (void*)Java_java_net_Inet4Address_init },
    { "Java_java_net_Inet6Address_init", (void*)Java_java_net_Inet6Address_init },
    { "Java_java_net_DatagramPacket_init", (void*)Java_java_net_DatagramPacket_init },
    { "IPv6_supported", (void*)IPv6_supported },
    { "NET_AllocSockaddr", (void*)NET_AllocSockaddr },
    { "NET_Bind", (void*)NET_Bind },
    { "NET_EnableFastTcpLoopback", (void*)NET_EnableFastTcpLoopback },
    { "NET_GetCurrentTime", (void*)NET_GetCurrentTime },
    { "NET_GetFileDescriptorID", (void*)NET_GetFileDescriptorID },
    { "NET_GetPortFromSockaddr", (void*)NET_GetPortFromSockaddr },
    { "NET_GetSockOpt", (void*)NET_GetSockOpt },
    { "NET_IPv4MappedToIPv4", (void*)NET_IPv4MappedToIPv4 },
    { "NET_InetAddressToSockaddr", (void*)NET_InetAddressToSockaddr },
    { "NET_IsEqual", (void*)NET_IsEqual },
    { "NET_IsIPv4Mapped", (void*)NET_IsIPv4Mapped },
    { "NET_IsZeroAddr", (void*)NET_IsZeroAddr },
    { "NET_MapSocketOption", (void*)NET_MapSocketOption },
    { "NET_SetSockOpt", (void*)NET_SetSockOpt },
    { "NET_SetTrafficClass", (void*)NET_SetTrafficClass },
    { "NET_ThrowByNameWithLastError", (void*)NET_ThrowByNameWithLastError },
    { "NET_ThrowCurrent", (void*)NET_ThrowCurrent },
    { "NET_ThrowNew", (void*)NET_ThrowNew },
    { "NET_Timeout", (void*)NET_Timeout },
    { "NET_TimeoutWithCurrentTime", (void*)NET_TimeoutWithCurrentTime },
    { "NET_Wait", (void*)NET_Wait },
    { "ThrowUnknownHostExceptionWithGaiError", (void*)ThrowUnknownHostExceptionWithGaiError },
    { "cmpScopeID", (void*)cmpScopeID },
    { "getDefaultIPv6Interface", (void*)getDefaultIPv6Interface },
    { "getDefaultScopeID", (void*)getDefaultScopeID },
    { "getScopeID", (void*)getScopeID },
    { "kernelIsV24", (void*)kernelIsV24 },
    { "parseExclusiveBindProperty", (void*)parseExclusiveBindProperty },
    { "platformInit", (void*)platformInit },
    { "printAddr", (void*)printAddr },
    { "setDefaultScopeID", (void*)setDefaultScopeID },
    { "Java_java_net_Inet4AddressImpl_getHostByAddr", (void*)Java_java_net_Inet4AddressImpl_getHostByAddr },
    { "Java_java_net_Inet4AddressImpl_getLocalHostName", (void*)Java_java_net_Inet4AddressImpl_getLocalHostName },
    { "Java_java_net_Inet4AddressImpl_isReachable0", (void*)Java_java_net_Inet4AddressImpl_isReachable0 },
    { "Java_java_net_Inet4AddressImpl_lookupAllHostAddr", (void*)Java_java_net_Inet4AddressImpl_lookupAllHostAddr },
    { "Java_java_net_Inet6AddressImpl_getHostByAddr", (void*)Java_java_net_Inet6AddressImpl_getHostByAddr },
    { "Java_java_net_Inet6AddressImpl_getLocalHostName", (void*)Java_java_net_Inet6AddressImpl_getLocalHostName },
    { "Java_java_net_Inet6AddressImpl_isReachable0", (void*)Java_java_net_Inet6AddressImpl_isReachable0 },
    { "Java_java_net_Inet6AddressImpl_lookupAllHostAddr", (void*)Java_java_net_Inet6AddressImpl_lookupAllHostAddr },
    { "Java_java_net_InetAddressImplFactory_isIPv6Supported", (void*)Java_java_net_InetAddressImplFactory_isIPv6Supported },
    { "Java_java_net_NetworkInterface_getAll", (void*)Java_java_net_NetworkInterface_getAll },
    { "Java_java_net_NetworkInterface_getByIndex0", (void*)Java_java_net_NetworkInterface_getByIndex0 },
    { "Java_java_net_NetworkInterface_getByInetAddress0", (void*)Java_java_net_NetworkInterface_getByInetAddress0 },
    { "Java_java_net_NetworkInterface_getByName0", (void*)Java_java_net_NetworkInterface_getByName0 },
    { "Java_java_net_NetworkInterface_getMTU0", (void*)Java_java_net_NetworkInterface_getMTU0 },
    { "Java_java_net_NetworkInterface_getMacAddr0", (void*)Java_java_net_NetworkInterface_getMacAddr0 },
    { "Java_java_net_NetworkInterface_init", (void*)Java_java_net_NetworkInterface_init },
    { "Java_java_net_NetworkInterface_isLoopback0", (void*)Java_java_net_NetworkInterface_isLoopback0 },
    { "Java_java_net_NetworkInterface_isP2P0", (void*)Java_java_net_NetworkInterface_isP2P0 },
    { "Java_java_net_NetworkInterface_isUp0", (void*)Java_java_net_NetworkInterface_isUp0 },
    { "Java_java_net_NetworkInterface_supportsMulticast0", (void*)Java_java_net_NetworkInterface_supportsMulticast0 },
    { "Java_java_net_PlainDatagramSocketImpl_bind0", (void*)Java_java_net_PlainDatagramSocketImpl_bind0 },
    { "Java_java_net_PlainDatagramSocketImpl_connect0", (void*)Java_java_net_PlainDatagramSocketImpl_connect0 },
    { "Java_java_net_PlainDatagramSocketImpl_dataAvailable", (void*)Java_java_net_PlainDatagramSocketImpl_dataAvailable },
    { "Java_java_net_PlainDatagramSocketImpl_datagramSocketClose", (void*)Java_java_net_PlainDatagramSocketImpl_datagramSocketClose },
    { "Java_java_net_PlainDatagramSocketImpl_datagramSocketCreate", (void*)Java_java_net_PlainDatagramSocketImpl_datagramSocketCreate },
    { "Java_java_net_PlainDatagramSocketImpl_disconnect0", (void*)Java_java_net_PlainDatagramSocketImpl_disconnect0 },
    { "Java_java_net_PlainDatagramSocketImpl_getTTL", (void*)Java_java_net_PlainDatagramSocketImpl_getTTL },
    { "Java_java_net_PlainDatagramSocketImpl_getTimeToLive", (void*)Java_java_net_PlainDatagramSocketImpl_getTimeToLive },
    { "Java_java_net_PlainDatagramSocketImpl_init", (void*)Java_java_net_PlainDatagramSocketImpl_init },
    { "Java_java_net_PlainDatagramSocketImpl_join", (void*)Java_java_net_PlainDatagramSocketImpl_join },
    { "Java_java_net_PlainDatagramSocketImpl_leave", (void*)Java_java_net_PlainDatagramSocketImpl_leave },
    { "Java_java_net_PlainDatagramSocketImpl_peek", (void*)Java_java_net_PlainDatagramSocketImpl_peek },
    { "Java_java_net_PlainDatagramSocketImpl_peekData", (void*)Java_java_net_PlainDatagramSocketImpl_peekData },
    { "Java_java_net_PlainDatagramSocketImpl_receive0", (void*)Java_java_net_PlainDatagramSocketImpl_receive0 },
    { "Java_java_net_PlainDatagramSocketImpl_send", (void*)Java_java_net_PlainDatagramSocketImpl_send },
    { "Java_java_net_PlainDatagramSocketImpl_setTTL", (void*)Java_java_net_PlainDatagramSocketImpl_setTTL },
    { "Java_java_net_PlainDatagramSocketImpl_setTimeToLive", (void*)Java_java_net_PlainDatagramSocketImpl_setTimeToLive },
    { "Java_java_net_PlainDatagramSocketImpl_socketGetOption", (void*)Java_java_net_PlainDatagramSocketImpl_socketGetOption },
    { "Java_java_net_PlainDatagramSocketImpl_socketSetOption0", (void*)Java_java_net_PlainDatagramSocketImpl_socketSetOption0 },
    { "getMulticastInterface", (void*)getMulticastInterface },
    { "Java_java_net_PlainSocketImpl_initProto", (void*)Java_java_net_PlainSocketImpl_initProto },
    { "Java_java_net_PlainSocketImpl_socketAccept", (void*)Java_java_net_PlainSocketImpl_socketAccept },
    { "Java_java_net_PlainSocketImpl_socketAvailable", (void*)Java_java_net_PlainSocketImpl_socketAvailable },
    { "Java_java_net_PlainSocketImpl_socketBind", (void*)Java_java_net_PlainSocketImpl_socketBind },
    { "Java_java_net_PlainSocketImpl_socketClose0", (void*)Java_java_net_PlainSocketImpl_socketClose0 },
    { "Java_java_net_PlainSocketImpl_socketConnect", (void*)Java_java_net_PlainSocketImpl_socketConnect },
    { "Java_java_net_PlainSocketImpl_socketCreate", (void*)Java_java_net_PlainSocketImpl_socketCreate },
    { "Java_java_net_PlainSocketImpl_socketGetOption", (void*)Java_java_net_PlainSocketImpl_socketGetOption },
    { "Java_java_net_PlainSocketImpl_socketListen", (void*)Java_java_net_PlainSocketImpl_socketListen },
    { "Java_java_net_PlainSocketImpl_socketSendUrgentData", (void*)Java_java_net_PlainSocketImpl_socketSendUrgentData },
    { "Java_java_net_PlainSocketImpl_socketSetOption0", (void*)Java_java_net_PlainSocketImpl_socketSetOption0 },
    { "Java_java_net_PlainSocketImpl_socketShutdown", (void*)Java_java_net_PlainSocketImpl_socketShutdown },
    { "Java_java_net_SocketInputStream_init", (void*)Java_java_net_SocketInputStream_init },
    { "Java_java_net_SocketInputStream_socketRead0", (void*)Java_java_net_SocketInputStream_socketRead0 },
    { "Java_java_net_SocketOutputStream_init", (void*)Java_java_net_SocketOutputStream_init },
    { "Java_java_net_SocketOutputStream_socketWrite0", (void*)Java_java_net_SocketOutputStream_socketWrite0 },
    { "NET_Accept", (void*)NET_Accept },
    { "NET_Connect", (void*)NET_Connect },
    { "NET_Dup2", (void*)NET_Dup2 },
    { "NET_NonBlockingRead", (void*)NET_NonBlockingRead },
    { "NET_Poll", (void*)NET_Poll },
    { "NET_Read", (void*)NET_Read },
    { "NET_ReadV", (void*)NET_ReadV },
    { "NET_RecvFrom", (void*)NET_RecvFrom },
    { "NET_Send", (void*)NET_Send },
    { "NET_SendTo", (void*)NET_SendTo },
    { "NET_SocketClose", (void*)NET_SocketClose },
    { "NET_Timeout0", (void*)NET_Timeout0 },
    { "NET_WriteV", (void*)NET_WriteV },
    { NULL, NULL }  /* sentinel */
};

#pragma clang diagnostic pop

/* Registry of statically-linked libraries.
 * JVM_LoadLibrary returns &jvm_static_libs[i] when path matches;
 * JVM_FindLibraryEntry then searches that entry's symbol table. */
const jvm_static_lib_entry_t jvm_static_libs[] = {
    { "/ikvm/bin/libiava.so", _syms_libiava_so },
    { "/ikvm/bin/libzip.so", _syms_libzip_so },
    { "/ikvm/bin/libnio.so", _syms_libnio_so },
    { "/ikvm/vin/libnet.so", _syms_libnet_so },
    { NULL, NULL }  /* sentinel */
};

const int jvm_static_libs_count = 4;
