/* Auto-generated by gen-static-libs.py — DO NOT EDIT.
 *
 * Regenerate with:
 *   python3 gen-static-libs.py /ikvm/bin/libiava.so:out/native/libiava.a
 *
 * Defines jvm_static_libs[], the registry used by jvm_emscripten_dynlib.c to
 * implement JVM_LoadLibrary / JVM_FindLibraryEntry without dlsym() or
 * -sMAIN_MODULE.  Each per-library symbol table was produced by running:
 *   /usr/bin/llvm-nm --defined-only --extern-only <archive>
 *
 * To add a library, re-run gen-static-libs.py with the new FAKE_PATH:ARCHIVE
 * pair.  To add symbols to an existing library, recompile the archive and
 * re-run the script.
 */

#include <stddef.h>  /* NULL */


/*
 * jvm_emscripten_dynlib.h
 *
 * Shared types and declarations for the Emscripten static library registry.
 * Included by both jvm_emscripten_dynlib.c (the logic) and by the .c file
 * produced by gen-static-libs.py (the data).
 */

#ifndef JVM_EMSCRIPTEN_DYNLIB_H
#define JVM_EMSCRIPTEN_DYNLIB_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * One symbol entry in a per-library lookup table.
 * name - the symbol name passed to JVM_FindLibraryEntry (e.g. "Java_Foo_bar")
 * ptr  - address of the symbol as resolved at compile time via a forward
 *        declaration in the generated file; stored as void* so that
 *        JVM_FindLibraryEntry can return it directly to the JNI caller.
 */
typedef struct {
    const char *name;
    void       *ptr;
} jvm_symbol_entry_t;

/*
 * One entry per statically-linked library.
 * path    - the exact string Java passes to JVM_LoadLibrary (e.g. "libjava.so"
 *           or the full path Java's launcher resolves to)
 * symbols - NULL-terminated array of symbol entries for this library,
 *           generated by gen-static-libs.py from llvm-nm output; NULL if the
 *           library was registered without an archive (empty symbol table).
 */
typedef struct {
    const char               *path;
    const jvm_symbol_entry_t *symbols;
} jvm_static_lib_entry_t;

/* Defined in the file generated by gen-static-libs.py */
extern const jvm_static_lib_entry_t jvm_static_libs[];
extern const int jvm_static_libs_count;

#ifdef __cplusplus
}
#endif

#endif /* JVM_EMSCRIPTEN_DYNLIB_H */


/* Forward declarations of every symbol referenced below.
 * Using empty parameter lists (K&R style) so the declarations
 * are compatible with any actual JNI signature without needing
 * prototypes.  The cast to void* is done in the tables below. */
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpedantic"
#pragma clang diagnostic ignored "-Wstrict-prototypes"

extern void JDK_execvpe();
extern void childProcess();
extern void closeDescriptors();
extern void closeSafely();
extern void execve_as_traditional_shell_script();
extern void execve_with_shell_fallback();
extern void initVectorFromBlock();
extern void isAsciiDigit();
extern void magicNumber();
extern void moveDescriptor();
extern void readFully();
extern void restartableDup2();
extern void restartableWrite();
extern void GetJavaProperties();
extern void GetStringPlatform();
extern void Java_java_lang_ProcessEnvironment_environ();
extern void Java_java_lang_UNIXProcess_destroyProcess();
extern void Java_java_lang_UNIXProcess_forkAndExec();
extern void Java_java_lang_UNIXProcess_init();
extern void Java_java_lang_UNIXProcess_waitForProcessExit();
extern void Java_java_lang_Double_doubleToRawLongBits();
extern void Java_java_lang_Double_longBitsToDouble();
extern void Java_java_lang_Float_floatToRawIntBits();
extern void Java_java_lang_Float_intBitsToFloat();
extern void Java_java_lang_StrictMath_IEEEremainder();
extern void Java_java_lang_StrictMath_acos();
extern void Java_java_lang_StrictMath_asin();
extern void Java_java_lang_StrictMath_atan();
extern void Java_java_lang_StrictMath_atan2();
extern void Java_java_lang_StrictMath_cbrt();
extern void Java_java_lang_StrictMath_cos();
extern void Java_java_lang_StrictMath_cosh();
extern void Java_java_lang_StrictMath_exp();
extern void Java_java_lang_StrictMath_expm1();
extern void Java_java_lang_StrictMath_hypot();
extern void Java_java_lang_StrictMath_log();
extern void Java_java_lang_StrictMath_log10();
extern void Java_java_lang_StrictMath_log1p();
extern void Java_java_lang_StrictMath_pow();
extern void Java_java_lang_StrictMath_sin();
extern void Java_java_lang_StrictMath_sinh();
extern void Java_java_lang_StrictMath_sqrt();
extern void Java_java_lang_StrictMath_tan();
extern void Java_java_lang_StrictMath_tanh();
extern void Java_java_lang_System_identityHashCode();
extern void Java_java_lang_System_initProperties();
extern void Java_java_lang_System_mapLibraryName();
extern void Java_java_lang_System_registerNatives();
extern void Java_java_lang_System_setErr0();
extern void Java_java_lang_System_setIn0();
extern void Java_java_lang_System_setOut0();
extern void fillI18nProps();
extern void Java_java_lang_reflect_Proxy_defineClass0();
extern void Java_java_io_FileInputStream_available0();
extern void Java_java_io_FileInputStream_initIDs();
extern void Java_java_io_FileInputStream_open0();
extern void Java_java_io_FileInputStream_read0();
extern void Java_java_io_FileInputStream_readBytes();
extern void Java_java_io_FileInputStream_skip0();
extern void readBytes();
extern void readSingle();
extern void throwFileNotFoundException();
extern void writeBytes();
extern void writeSingle();
extern void Java_java_io_ObjectInputStream_bytesToDoubles();
extern void Java_java_io_ObjectInputStream_bytesToFloats();
extern void Java_java_io_ObjectOutputStream_doublesToBytes();
extern void Java_java_io_ObjectOutputStream_floatsToBytes();
extern void Java_java_io_ObjectStreamClass_hasStaticInitializer();
extern void Java_java_io_ObjectStreamClass_initNative();
extern void Java_java_io_RandomAccessFile_getFilePointer();
extern void Java_java_io_RandomAccessFile_initIDs();
extern void Java_java_io_RandomAccessFile_length();
extern void Java_java_io_RandomAccessFile_open0();
extern void Java_java_io_RandomAccessFile_read0();
extern void Java_java_io_RandomAccessFile_readBytes();
extern void Java_java_io_RandomAccessFile_seek0();
extern void Java_java_io_RandomAccessFile_setLength();
extern void Java_java_io_RandomAccessFile_write0();
extern void Java_java_io_RandomAccessFile_writeBytes();
extern void canonicalize();
extern void Java_java_io_Console_echo();
extern void Java_java_io_Console_encoding();
extern void Java_java_io_Console_istty();
extern void Java_java_io_FileDescriptor_initIDs();
extern void Java_java_io_FileDescriptor_sync();
extern void Java_java_io_FileInputStream_close0();
extern void Java_java_io_FileOutputStream_close0();
extern void Java_java_io_FileOutputStream_initIDs();
extern void Java_java_io_FileOutputStream_open0();
extern void Java_java_io_FileOutputStream_write();
extern void Java_java_io_FileOutputStream_writeBytes();
extern void fileClose();
extern void fileOpen();
extern void getLastErrorString();
extern void handleAvailable();
extern void handleOpen();
extern void handleRead();
extern void handleSetLength();
extern void handleWrite();
extern void Java_java_io_RandomAccessFile_close0();
extern void Java_java_io_UnixFileSystem_canonicalize0();
extern void Java_java_io_UnixFileSystem_checkAccess();
extern void Java_java_io_UnixFileSystem_createDirectory();
extern void Java_java_io_UnixFileSystem_createFileExclusively();
extern void Java_java_io_UnixFileSystem_delete0();
extern void Java_java_io_UnixFileSystem_getBooleanAttributes0();
extern void Java_java_io_UnixFileSystem_getLastModifiedTime();
extern void Java_java_io_UnixFileSystem_getLength();
extern void Java_java_io_UnixFileSystem_getSpace();
extern void Java_java_io_UnixFileSystem_initIDs();
extern void Java_java_io_UnixFileSystem_list();
extern void Java_java_io_UnixFileSystem_rename0();
extern void Java_java_io_UnixFileSystem_setLastModifiedTime();
extern void Java_java_io_UnixFileSystem_setPermission();
extern void Java_java_io_UnixFileSystem_setReadOnly();
extern void Java_java_nio_Bits_copySwapMemory0();
extern void JNI_OnLoad();
extern void JDK_GetVersionInfo0();
extern void jio_fprintf();
extern void jio_snprintf();
extern void Canonicalize();
extern void GetStringPlatformChars();
extern void JNU_CallMethodByName();
extern void JNU_CallMethodByNameV();
extern void JNU_CallStaticMethodByName();
extern void JNU_ClassClass();
extern void JNU_ClassObject();
extern void JNU_ClassString();
extern void JNU_ClassThrowable();
extern void JNU_CopyObjectArray();
extern void JNU_Equals();
extern void JNU_GetEnv();
extern void JNU_GetFieldByName();
extern void JNU_GetStaticFieldByName();
extern void JNU_GetStringPlatformChars();
extern void JNU_IsInstanceOfByName();
extern void JNU_MonitorWait();
extern void JNU_NewObjectByName();
extern void JNU_NewStringPlatform();
extern void JNU_Notify();
extern void JNU_NotifyAll();
extern void JNU_PrintClass();
extern void JNU_PrintString();
extern void JNU_ReleaseStringPlatformChars();
extern void JNU_SetFieldByName();
extern void JNU_SetStaticFieldByName();
extern void JNU_ThrowArrayIndexOutOfBoundsException();
extern void JNU_ThrowByName();
extern void JNU_ThrowByNameWithLastError();
extern void JNU_ThrowByNameWithMessageAndLastError();
extern void JNU_ThrowClassNotFoundException();
extern void JNU_ThrowIOException();
extern void JNU_ThrowIOExceptionWithLastError();
extern void JNU_ThrowIllegalAccessError();
extern void JNU_ThrowIllegalAccessException();
extern void JNU_ThrowIllegalArgumentException();
extern void JNU_ThrowInstantiationException();
extern void JNU_ThrowInternalError();
extern void JNU_ThrowNoSuchFieldError();
extern void JNU_ThrowNoSuchFieldException();
extern void JNU_ThrowNoSuchMethodError();
extern void JNU_ThrowNoSuchMethodException();
extern void JNU_ThrowNullPointerException();
extern void JNU_ThrowNumberFormatException();
extern void JNU_ThrowOutOfMemoryError();
extern void JNU_ThrowStringIndexOutOfBoundsException();
extern void JNU_ToString();
extern void NewStringPlatform();
extern void getFastEncoding();
extern void initializeEncoding();
extern void Java_sun_misc_MessageUtils_toStderr();
extern void Java_sun_misc_MessageUtils_toStdout();
extern void Java_sun_misc_NativeSignalHandler_handle0();
extern void Java_sun_misc_Version_getJdkSpecialVersion();
extern void Java_sun_misc_Version_getJdkVersionInfo();
extern void Java_sun_misc_Version_getJvmSpecialVersion();
extern void Java_sun_misc_Version_getJvmVersionInfo();
extern void Java_sun_misc_VMSupport_getVMTemporaryDirectory();
extern void Java_sun_misc_VMSupport_initAgentProperties();
extern void Java_java_util_TimeZone_getSystemGMTOffsetID();
extern void Java_java_util_TimeZone_getSystemTimeZoneID();
extern void JDK_FindJvmEntry();
extern void JDK_InitJvmHandle();
extern void buildJniFunctionName();
extern void getErrorString();
extern void getProcessHandle();
extern void nativeGetStringPlatformChars();
extern void nativeNewStringPlatform();
extern void Java_java_util_prefs_FileSystemPreferences_chmod();
extern void Java_java_util_prefs_FileSystemPreferences_lockFile0();
extern void Java_java_util_prefs_FileSystemPreferences_unlockFile0();
extern void Java_java_util_logging_FileHandler_isSetUID();
extern void findJavaTZ_md();
extern void getGMTOffsetID();
extern void Java_jdk_internal_platform_CgroupMetrics_getTotalMemorySize0();
extern void Java_jdk_internal_platform_CgroupMetrics_isUseContainerSupport();

/* Symbol table for "/ikvm/bin/libiava.so" (199 symbols) */
static const jvm_symbol_entry_t _syms_libiava_so[] = {
    { "JDK_execvpe", (void*)JDK_execvpe },
    { "childProcess", (void*)childProcess },
    { "closeDescriptors", (void*)closeDescriptors },
    { "closeSafely", (void*)closeSafely },
    { "execve_as_traditional_shell_script", (void*)execve_as_traditional_shell_script },
    { "execve_with_shell_fallback", (void*)execve_with_shell_fallback },
    { "initVectorFromBlock", (void*)initVectorFromBlock },
    { "isAsciiDigit", (void*)isAsciiDigit },
    { "magicNumber", (void*)magicNumber },
    { "moveDescriptor", (void*)moveDescriptor },
    { "readFully", (void*)readFully },
    { "restartableDup2", (void*)restartableDup2 },
    { "restartableWrite", (void*)restartableWrite },
    { "GetJavaProperties", (void*)GetJavaProperties },
    { "GetStringPlatform", (void*)GetStringPlatform },
    { "Java_java_lang_ProcessEnvironment_environ", (void*)Java_java_lang_ProcessEnvironment_environ },
    { "Java_java_lang_UNIXProcess_destroyProcess", (void*)Java_java_lang_UNIXProcess_destroyProcess },
    { "Java_java_lang_UNIXProcess_forkAndExec", (void*)Java_java_lang_UNIXProcess_forkAndExec },
    { "Java_java_lang_UNIXProcess_init", (void*)Java_java_lang_UNIXProcess_init },
    { "Java_java_lang_UNIXProcess_waitForProcessExit", (void*)Java_java_lang_UNIXProcess_waitForProcessExit },
    { "Java_java_lang_Double_doubleToRawLongBits", (void*)Java_java_lang_Double_doubleToRawLongBits },
    { "Java_java_lang_Double_longBitsToDouble", (void*)Java_java_lang_Double_longBitsToDouble },
    { "Java_java_lang_Float_floatToRawIntBits", (void*)Java_java_lang_Float_floatToRawIntBits },
    { "Java_java_lang_Float_intBitsToFloat", (void*)Java_java_lang_Float_intBitsToFloat },
    { "Java_java_lang_StrictMath_IEEEremainder", (void*)Java_java_lang_StrictMath_IEEEremainder },
    { "Java_java_lang_StrictMath_acos", (void*)Java_java_lang_StrictMath_acos },
    { "Java_java_lang_StrictMath_asin", (void*)Java_java_lang_StrictMath_asin },
    { "Java_java_lang_StrictMath_atan", (void*)Java_java_lang_StrictMath_atan },
    { "Java_java_lang_StrictMath_atan2", (void*)Java_java_lang_StrictMath_atan2 },
    { "Java_java_lang_StrictMath_cbrt", (void*)Java_java_lang_StrictMath_cbrt },
    { "Java_java_lang_StrictMath_cos", (void*)Java_java_lang_StrictMath_cos },
    { "Java_java_lang_StrictMath_cosh", (void*)Java_java_lang_StrictMath_cosh },
    { "Java_java_lang_StrictMath_exp", (void*)Java_java_lang_StrictMath_exp },
    { "Java_java_lang_StrictMath_expm1", (void*)Java_java_lang_StrictMath_expm1 },
    { "Java_java_lang_StrictMath_hypot", (void*)Java_java_lang_StrictMath_hypot },
    { "Java_java_lang_StrictMath_log", (void*)Java_java_lang_StrictMath_log },
    { "Java_java_lang_StrictMath_log10", (void*)Java_java_lang_StrictMath_log10 },
    { "Java_java_lang_StrictMath_log1p", (void*)Java_java_lang_StrictMath_log1p },
    { "Java_java_lang_StrictMath_pow", (void*)Java_java_lang_StrictMath_pow },
    { "Java_java_lang_StrictMath_sin", (void*)Java_java_lang_StrictMath_sin },
    { "Java_java_lang_StrictMath_sinh", (void*)Java_java_lang_StrictMath_sinh },
    { "Java_java_lang_StrictMath_sqrt", (void*)Java_java_lang_StrictMath_sqrt },
    { "Java_java_lang_StrictMath_tan", (void*)Java_java_lang_StrictMath_tan },
    { "Java_java_lang_StrictMath_tanh", (void*)Java_java_lang_StrictMath_tanh },
    { "Java_java_lang_System_identityHashCode", (void*)Java_java_lang_System_identityHashCode },
    { "Java_java_lang_System_initProperties", (void*)Java_java_lang_System_initProperties },
    { "Java_java_lang_System_mapLibraryName", (void*)Java_java_lang_System_mapLibraryName },
    { "Java_java_lang_System_registerNatives", (void*)Java_java_lang_System_registerNatives },
    { "Java_java_lang_System_setErr0", (void*)Java_java_lang_System_setErr0 },
    { "Java_java_lang_System_setIn0", (void*)Java_java_lang_System_setIn0 },
    { "Java_java_lang_System_setOut0", (void*)Java_java_lang_System_setOut0 },
    { "fillI18nProps", (void*)fillI18nProps },
    { "Java_java_lang_reflect_Proxy_defineClass0", (void*)Java_java_lang_reflect_Proxy_defineClass0 },
    { "Java_java_io_FileInputStream_available0", (void*)Java_java_io_FileInputStream_available0 },
    { "Java_java_io_FileInputStream_initIDs", (void*)Java_java_io_FileInputStream_initIDs },
    { "Java_java_io_FileInputStream_open0", (void*)Java_java_io_FileInputStream_open0 },
    { "Java_java_io_FileInputStream_read0", (void*)Java_java_io_FileInputStream_read0 },
    { "Java_java_io_FileInputStream_readBytes", (void*)Java_java_io_FileInputStream_readBytes },
    { "Java_java_io_FileInputStream_skip0", (void*)Java_java_io_FileInputStream_skip0 },
    { "readBytes", (void*)readBytes },
    { "readSingle", (void*)readSingle },
    { "throwFileNotFoundException", (void*)throwFileNotFoundException },
    { "writeBytes", (void*)writeBytes },
    { "writeSingle", (void*)writeSingle },
    { "Java_java_io_ObjectInputStream_bytesToDoubles", (void*)Java_java_io_ObjectInputStream_bytesToDoubles },
    { "Java_java_io_ObjectInputStream_bytesToFloats", (void*)Java_java_io_ObjectInputStream_bytesToFloats },
    { "Java_java_io_ObjectOutputStream_doublesToBytes", (void*)Java_java_io_ObjectOutputStream_doublesToBytes },
    { "Java_java_io_ObjectOutputStream_floatsToBytes", (void*)Java_java_io_ObjectOutputStream_floatsToBytes },
    { "Java_java_io_ObjectStreamClass_hasStaticInitializer", (void*)Java_java_io_ObjectStreamClass_hasStaticInitializer },
    { "Java_java_io_ObjectStreamClass_initNative", (void*)Java_java_io_ObjectStreamClass_initNative },
    { "Java_java_io_RandomAccessFile_getFilePointer", (void*)Java_java_io_RandomAccessFile_getFilePointer },
    { "Java_java_io_RandomAccessFile_initIDs", (void*)Java_java_io_RandomAccessFile_initIDs },
    { "Java_java_io_RandomAccessFile_length", (void*)Java_java_io_RandomAccessFile_length },
    { "Java_java_io_RandomAccessFile_open0", (void*)Java_java_io_RandomAccessFile_open0 },
    { "Java_java_io_RandomAccessFile_read0", (void*)Java_java_io_RandomAccessFile_read0 },
    { "Java_java_io_RandomAccessFile_readBytes", (void*)Java_java_io_RandomAccessFile_readBytes },
    { "Java_java_io_RandomAccessFile_seek0", (void*)Java_java_io_RandomAccessFile_seek0 },
    { "Java_java_io_RandomAccessFile_setLength", (void*)Java_java_io_RandomAccessFile_setLength },
    { "Java_java_io_RandomAccessFile_write0", (void*)Java_java_io_RandomAccessFile_write0 },
    { "Java_java_io_RandomAccessFile_writeBytes", (void*)Java_java_io_RandomAccessFile_writeBytes },
    { "canonicalize", (void*)canonicalize },
    { "Java_java_io_Console_echo", (void*)Java_java_io_Console_echo },
    { "Java_java_io_Console_encoding", (void*)Java_java_io_Console_encoding },
    { "Java_java_io_Console_istty", (void*)Java_java_io_Console_istty },
    { "Java_java_io_FileDescriptor_initIDs", (void*)Java_java_io_FileDescriptor_initIDs },
    { "Java_java_io_FileDescriptor_sync", (void*)Java_java_io_FileDescriptor_sync },
    { "Java_java_io_FileInputStream_close0", (void*)Java_java_io_FileInputStream_close0 },
    { "Java_java_io_FileOutputStream_close0", (void*)Java_java_io_FileOutputStream_close0 },
    { "Java_java_io_FileOutputStream_initIDs", (void*)Java_java_io_FileOutputStream_initIDs },
    { "Java_java_io_FileOutputStream_open0", (void*)Java_java_io_FileOutputStream_open0 },
    { "Java_java_io_FileOutputStream_write", (void*)Java_java_io_FileOutputStream_write },
    { "Java_java_io_FileOutputStream_writeBytes", (void*)Java_java_io_FileOutputStream_writeBytes },
    { "fileClose", (void*)fileClose },
    { "fileOpen", (void*)fileOpen },
    { "getLastErrorString", (void*)getLastErrorString },
    { "handleAvailable", (void*)handleAvailable },
    { "handleOpen", (void*)handleOpen },
    { "handleRead", (void*)handleRead },
    { "handleSetLength", (void*)handleSetLength },
    { "handleWrite", (void*)handleWrite },
    { "Java_java_io_RandomAccessFile_close0", (void*)Java_java_io_RandomAccessFile_close0 },
    { "Java_java_io_UnixFileSystem_canonicalize0", (void*)Java_java_io_UnixFileSystem_canonicalize0 },
    { "Java_java_io_UnixFileSystem_checkAccess", (void*)Java_java_io_UnixFileSystem_checkAccess },
    { "Java_java_io_UnixFileSystem_createDirectory", (void*)Java_java_io_UnixFileSystem_createDirectory },
    { "Java_java_io_UnixFileSystem_createFileExclusively", (void*)Java_java_io_UnixFileSystem_createFileExclusively },
    { "Java_java_io_UnixFileSystem_delete0", (void*)Java_java_io_UnixFileSystem_delete0 },
    { "Java_java_io_UnixFileSystem_getBooleanAttributes0", (void*)Java_java_io_UnixFileSystem_getBooleanAttributes0 },
    { "Java_java_io_UnixFileSystem_getLastModifiedTime", (void*)Java_java_io_UnixFileSystem_getLastModifiedTime },
    { "Java_java_io_UnixFileSystem_getLength", (void*)Java_java_io_UnixFileSystem_getLength },
    { "Java_java_io_UnixFileSystem_getSpace", (void*)Java_java_io_UnixFileSystem_getSpace },
    { "Java_java_io_UnixFileSystem_initIDs", (void*)Java_java_io_UnixFileSystem_initIDs },
    { "Java_java_io_UnixFileSystem_list", (void*)Java_java_io_UnixFileSystem_list },
    { "Java_java_io_UnixFileSystem_rename0", (void*)Java_java_io_UnixFileSystem_rename0 },
    { "Java_java_io_UnixFileSystem_setLastModifiedTime", (void*)Java_java_io_UnixFileSystem_setLastModifiedTime },
    { "Java_java_io_UnixFileSystem_setPermission", (void*)Java_java_io_UnixFileSystem_setPermission },
    { "Java_java_io_UnixFileSystem_setReadOnly", (void*)Java_java_io_UnixFileSystem_setReadOnly },
    { "Java_java_nio_Bits_copySwapMemory0", (void*)Java_java_nio_Bits_copySwapMemory0 },
    { "JNI_OnLoad", (void*)JNI_OnLoad },
    { "JDK_GetVersionInfo0", (void*)JDK_GetVersionInfo0 },
    { "jio_fprintf", (void*)jio_fprintf },
    { "jio_snprintf", (void*)jio_snprintf },
    { "Canonicalize", (void*)Canonicalize },
    { "GetStringPlatformChars", (void*)GetStringPlatformChars },
    { "JNU_CallMethodByName", (void*)JNU_CallMethodByName },
    { "JNU_CallMethodByNameV", (void*)JNU_CallMethodByNameV },
    { "JNU_CallStaticMethodByName", (void*)JNU_CallStaticMethodByName },
    { "JNU_ClassClass", (void*)JNU_ClassClass },
    { "JNU_ClassObject", (void*)JNU_ClassObject },
    { "JNU_ClassString", (void*)JNU_ClassString },
    { "JNU_ClassThrowable", (void*)JNU_ClassThrowable },
    { "JNU_CopyObjectArray", (void*)JNU_CopyObjectArray },
    { "JNU_Equals", (void*)JNU_Equals },
    { "JNU_GetEnv", (void*)JNU_GetEnv },
    { "JNU_GetFieldByName", (void*)JNU_GetFieldByName },
    { "JNU_GetStaticFieldByName", (void*)JNU_GetStaticFieldByName },
    { "JNU_GetStringPlatformChars", (void*)JNU_GetStringPlatformChars },
    { "JNU_IsInstanceOfByName", (void*)JNU_IsInstanceOfByName },
    { "JNU_MonitorWait", (void*)JNU_MonitorWait },
    { "JNU_NewObjectByName", (void*)JNU_NewObjectByName },
    { "JNU_NewStringPlatform", (void*)JNU_NewStringPlatform },
    { "JNU_Notify", (void*)JNU_Notify },
    { "JNU_NotifyAll", (void*)JNU_NotifyAll },
    { "JNU_PrintClass", (void*)JNU_PrintClass },
    { "JNU_PrintString", (void*)JNU_PrintString },
    { "JNU_ReleaseStringPlatformChars", (void*)JNU_ReleaseStringPlatformChars },
    { "JNU_SetFieldByName", (void*)JNU_SetFieldByName },
    { "JNU_SetStaticFieldByName", (void*)JNU_SetStaticFieldByName },
    { "JNU_ThrowArrayIndexOutOfBoundsException", (void*)JNU_ThrowArrayIndexOutOfBoundsException },
    { "JNU_ThrowByName", (void*)JNU_ThrowByName },
    { "JNU_ThrowByNameWithLastError", (void*)JNU_ThrowByNameWithLastError },
    { "JNU_ThrowByNameWithMessageAndLastError", (void*)JNU_ThrowByNameWithMessageAndLastError },
    { "JNU_ThrowClassNotFoundException", (void*)JNU_ThrowClassNotFoundException },
    { "JNU_ThrowIOException", (void*)JNU_ThrowIOException },
    { "JNU_ThrowIOExceptionWithLastError", (void*)JNU_ThrowIOExceptionWithLastError },
    { "JNU_ThrowIllegalAccessError", (void*)JNU_ThrowIllegalAccessError },
    { "JNU_ThrowIllegalAccessException", (void*)JNU_ThrowIllegalAccessException },
    { "JNU_ThrowIllegalArgumentException", (void*)JNU_ThrowIllegalArgumentException },
    { "JNU_ThrowInstantiationException", (void*)JNU_ThrowInstantiationException },
    { "JNU_ThrowInternalError", (void*)JNU_ThrowInternalError },
    { "JNU_ThrowNoSuchFieldError", (void*)JNU_ThrowNoSuchFieldError },
    { "JNU_ThrowNoSuchFieldException", (void*)JNU_ThrowNoSuchFieldException },
    { "JNU_ThrowNoSuchMethodError", (void*)JNU_ThrowNoSuchMethodError },
    { "JNU_ThrowNoSuchMethodException", (void*)JNU_ThrowNoSuchMethodException },
    { "JNU_ThrowNullPointerException", (void*)JNU_ThrowNullPointerException },
    { "JNU_ThrowNumberFormatException", (void*)JNU_ThrowNumberFormatException },
    { "JNU_ThrowOutOfMemoryError", (void*)JNU_ThrowOutOfMemoryError },
    { "JNU_ThrowStringIndexOutOfBoundsException", (void*)JNU_ThrowStringIndexOutOfBoundsException },
    { "JNU_ToString", (void*)JNU_ToString },
    { "NewStringPlatform", (void*)NewStringPlatform },
    { "getFastEncoding", (void*)getFastEncoding },
    { "initializeEncoding", (void*)initializeEncoding },
    { "Java_sun_misc_MessageUtils_toStderr", (void*)Java_sun_misc_MessageUtils_toStderr },
    { "Java_sun_misc_MessageUtils_toStdout", (void*)Java_sun_misc_MessageUtils_toStdout },
    { "Java_sun_misc_NativeSignalHandler_handle0", (void*)Java_sun_misc_NativeSignalHandler_handle0 },
    { "Java_sun_misc_Version_getJdkSpecialVersion", (void*)Java_sun_misc_Version_getJdkSpecialVersion },
    { "Java_sun_misc_Version_getJdkVersionInfo", (void*)Java_sun_misc_Version_getJdkVersionInfo },
    { "Java_sun_misc_Version_getJvmSpecialVersion", (void*)Java_sun_misc_Version_getJvmSpecialVersion },
    { "Java_sun_misc_Version_getJvmVersionInfo", (void*)Java_sun_misc_Version_getJvmVersionInfo },
    { "Java_sun_misc_VMSupport_getVMTemporaryDirectory", (void*)Java_sun_misc_VMSupport_getVMTemporaryDirectory },
    { "Java_sun_misc_VMSupport_initAgentProperties", (void*)Java_sun_misc_VMSupport_initAgentProperties },
    { "Java_java_util_TimeZone_getSystemGMTOffsetID", (void*)Java_java_util_TimeZone_getSystemGMTOffsetID },
    { "Java_java_util_TimeZone_getSystemTimeZoneID", (void*)Java_java_util_TimeZone_getSystemTimeZoneID },
    { "JDK_FindJvmEntry", (void*)JDK_FindJvmEntry },
    { "JDK_InitJvmHandle", (void*)JDK_InitJvmHandle },
    { "buildJniFunctionName", (void*)buildJniFunctionName },
    { "getErrorString", (void*)getErrorString },
    { "getProcessHandle", (void*)getProcessHandle },
    { "nativeGetStringPlatformChars", (void*)nativeGetStringPlatformChars },
    { "nativeNewStringPlatform", (void*)nativeNewStringPlatform },
    { "Java_java_util_prefs_FileSystemPreferences_chmod", (void*)Java_java_util_prefs_FileSystemPreferences_chmod },
    { "Java_java_util_prefs_FileSystemPreferences_lockFile0", (void*)Java_java_util_prefs_FileSystemPreferences_lockFile0 },
    { "Java_java_util_prefs_FileSystemPreferences_unlockFile0", (void*)Java_java_util_prefs_FileSystemPreferences_unlockFile0 },
    { "Java_java_util_logging_FileHandler_isSetUID", (void*)Java_java_util_logging_FileHandler_isSetUID },
    { "findJavaTZ_md", (void*)findJavaTZ_md },
    { "getGMTOffsetID", (void*)getGMTOffsetID },
    { "Java_jdk_internal_platform_CgroupMetrics_getTotalMemorySize0", (void*)Java_jdk_internal_platform_CgroupMetrics_getTotalMemorySize0 },
    { "Java_jdk_internal_platform_CgroupMetrics_isUseContainerSupport", (void*)Java_jdk_internal_platform_CgroupMetrics_isUseContainerSupport },
    { NULL, NULL }  /* sentinel */
};

#pragma clang diagnostic pop

/* Registry of statically-linked libraries.
 * JVM_LoadLibrary returns &jvm_static_libs[i] when path matches;
 * JVM_FindLibraryEntry then searches that entry's symbol table. */
const jvm_static_lib_entry_t jvm_static_libs[] = {
    { "/ikvm/bin/libiava.so", _syms_libiava_so },
    { NULL, NULL }  /* sentinel */
};

const int jvm_static_libs_count = 1;
